### ISSUE TITLE
Add an option to automatically open TF2 after launching the tool

### ISSUE THREAD

**Issue by Jonttm** [PazerOP/tf2_bot_detector#105]
After reading #94 I thought this would be a good idea since you have to launch the tool before launching TF2 anyways and why would you have it open with TF2 closed?

**Comment by ClusterConsultant** [comment]
The rcon update could close this issue

**Comment by OceanFoxy** [comment]
I like the new setup flow with a launch TF2 button and still think clicking the button should be default, but having the option would be nice. Just minor convenience at this point. Just like a checkbox in the settings:

☑ Automatically launch TF2

(it should check if hl2.exe is running before attempting to auto launch)

**Comment by ClusterConsultant** [comment]
Closed by commit 7cef149

**Comment by PazerOP** [comment]
reopening because it is not yet merged into master. the disorganization today is mostly because i am experimenting trying to find an optimal workflow
