### ISSUE TITLE
Tool using Rcon instead of the old method? Potential linux support?

### ISSUE THREAD

**Issue by The-personified-devil** [PazerOP/tf2_bot_detector#109]
Is this tool now using local rcon instead of the `-hijack` method (This is sadly not really documented.)? Would this add the possibility of support for other platforms?

Thanks

**Comment by PazerOP** [comment]
Yes, the next version will be entirely reliant on a local rcon connection instead of hijack. This improves performance, and opens up the door to support for other platforms.
