### ISSUE TITLE
Autoreport marked cheaters

### ISSUE THREAD

**Issue by The-personified-devil** [PazerOP/tf2_bot_detector#111]
It seems as if valve actually kinda cares if an account gets reported a lot (They did a ban wave on bots.). If the tool also reports marked cheaters and not just kicks them, they would be banned (This would ruin any attempts of the bot hoster to give the bots premium.). I sadly didn't find a console commands for it (I hope there's another way.).
Thanks

**Comment by ClusterConsultant** [comment]
Would be useful, I'm not entirely sure if it is possible. If so would be a good addition.

**Comment by lnx00** [comment]
I don't think this is possible. But I wonder if the "cheater" kick reason has any impact on the Account. Maybe that counts as a report too

**Comment by The-personified-devil** [comment]
I myself didn't find a console command for it (It's probably not possible.). As far as I know getting kicked often can temporarily ban you from the server you were kicked from, but nothing else at the moment. It's always a hindering for the bot hoster having bots banned, even if we don't reduce the number of bots there are, we at least exhaust the bot hoster.
If there is definitely no way of implementing this, then I'll close the issue.

**Comment by ClusterConsultant** [comment]
I looked through all the documented commands on the dev docs and didn't see anything. Just stuff for the abuse report GUI which would not be automated.

**Comment by The-personified-devil** [comment]
Then I'll close this.

**Comment by ldesgoui** [comment]
There's always hidden commands, but in this case, according to the 2017 source leak, there are no commands to handle this. Code is in `game/client/tf/vgui/report_player_dialog.cpp`

**Comment by PabloDinella** [comment]
Maybe there could be a list of detected cheaters with the link to their profiles, so the user can manually report them if he wants to?

**Comment by PazerOP** [comment]
It's generally not worth it to report people's steam profiles if all they're doing is cheating. My understanding is that profile reports are reviewed by steam community moderators, who do not have any information about what that player is actually doing in TF2. Because of this, they can't actually take action (at least, I have never heard of it happening) based on reports about ingame behavior.
