### ISSUE TITLE
Implementation to counter auto-leave bots

### ISSUE THREAD

**Issue by The-personified-devil** [PazerOP/tf2_bot_detector#119]
I found a video on r/tf2 showing a strategy to counter the auto leave bots that can get around vote kicks. Could something similar be implemented?

**Comment by ClusterConsultant** [comment]
post a link?

**Comment by The-personified-devil** [comment]
Sorry... Here you go [Auto-leave bots in tf2, how to deal with them.](https://youtu.be/LQjmdqmm8xg)

**Comment by ClusterConsultant** [comment]
The application already does this afaik. It auto kicks bots as soon as it can

**Comment by The-personified-devil** [comment]
Right. That's already implemented, because it kicks as fast as possible. I'm dumb.
