### ISSUE TITLE
TF2 Not launching

### ISSUE THREAD

**Issue by Haxorzz** [PazerOP/tf2_bot_detector#131]
launching tf2 from the tool will launch the excecutable... you wait a bit.... and then it will crash with "couldnt allocate any server ip port" That's cool

**Comment by ClusterConsultant** [comment]
What version of windows are you on? What are the arguments that appear?

**Comment by ClusterConsultant** [comment]
https://user-images.githubusercontent.com/66532903/86859388-c1060c00-c07f-11ea-8583-621a9a112851.png

**Comment by Haxorzz** [comment]
Windows 10, and no arguments appear, but when I launch tf2 (Through this tool not steam) It'll say that an insatnce of tf2 is already running? "Well ofc it is you just launched it" That's all I know

**Comment by Haxorzz** [comment]
Aight restarting the tool has temporarily fixed it... but what caused it?

**Comment by Haxorzz** [comment]
Happened again... I think it's caused by opening tf2, closing it, and shortly after trying to open it with the tool... You cant open tf2 with the tool if you just closed it within like 15 seconds

**Comment by PazerOP** [comment]
@Haxorzz can you post your tf2bd log here (in the `logs` folder next to tf2_bot_detector.exe), or dm me it on discord? pazer#8137

**Comment by Haxorzz** [comment]
[logs.zip](https://github.com/PazerOP/tf2_bot_detector/files/4896136/logs.zip)
Here ya go!
Although just looking through them, I didnt see anything suspicious.

**Comment by PazerOP** [comment]
Hmm... is it possible for you to make a screen recording? I'm still not exactly clear on what's happening. You mention it might be caused by opening tf2, closing it, then trying to reopen it quickly via the tool.. why not just open it with the tool to begin with? There are some required command line arguments in order for the tool to properly communicate with tf2, so you have to start it through the tool. Starting the game normally won't let it work with tf2bd.

**Comment by Haxorzz** [comment]
ye that's true I'll make a screen recording if you want... I'm just so used to opening tf2 via steam or a shortcut that I have to close it and then open it via the tool...

**Comment by Haxorzz** [comment]
This happened again... I had NOT opened tf2 in a really long time, yet it still gave me this error... something else is going on

**Comment by ParzivalWolfram** [comment]
> This happened again... I had NOT opened tf2 in a really long time, yet it still gave me this error... something else is going on

If memory serves, TF2 checks for open copies by looking for a process with name "hl2.exe". Try seeing if any are sticking around in memory by going to the Task Manager, pressing "More Options" in the bottom right if presented with a small, simple box without tabs, then clicking the "Details" tab towards the right of the window.

Alternatively, your copy may be busted, try verifying or reinstalling TF2.

**Comment by Haxorzz** [comment]
I know how to use task manager :P
My pc legit just booted a couple of mins ago... and no It's not fast boot or tf2 because closing and opening the tool always makes it work again...

**Comment by ParzivalWolfram** [comment]
Not many people know how to use Task Manager, i'm just ensuring you would
know how, my apologies. Anyways, Fast Startup causes issues in itself,
aside from the obvious carry-over-all-problems issues, so it's usually best
to turn it off in the first place (it's not actually faster after the first
3 or 4 shutdowns, either, and it tears SSDs to shreds.)

Back on topic, can you check if TF2BD fails to die? That may also be an
issue...

**Comment by PazerOP** [comment]
@Haxorzz could you please provide a screen recording of this issue happening?

**Comment by ClusterConsultant** [comment]
@Haxorzz do you have any update on this?

**Comment by Haxorzz** [comment]
@ClusterConsultant I kinda stopped playing tf2 a couple of weeks later, so sadly no... Also the video footage is lost in my old setup

**Comment by ClusterConsultant** [comment]
Well that is unfortunate. I have seen this issue crop up myself but it's rare and hard to reproduce at least on my system. Unless this becomes a major issue I'm going to bump down the priority and it will likely remain on the back burner.

**Comment by ClusterConsultant** [comment]
This has not cropped up in some time, and the suspected root cause should be addressed with port range specifications no available. This issue will be closed on 25/01/2021 if nothing more is heard
