### ISSUE TITLE
Discord Rich Presense

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/tf2_bot_detector#135]
it's very easy to implement, so why not ¯\\\_(ツ)\_/¯

We can show info like time in server, current map, etc. Demo parsing would allow us to show class, score, etc.

**Comment by ClusterConsultant** [comment]
This is implemented with the exception of demo related things (which are oos for this issue and version) and remaining images, tracked by #183

**Comment by PazerOP** [comment]
Closing this because #183 is closed, and no more work is expected to be done on DRP any time soon. Will be waiting for demo parsing for that, and a separate issue will be made to track progress at that point.
