### ISSUE TITLE
Using steam to report bots

### ISSUE THREAD

**Issue by The-personified-devil** [PazerOP/tf2_bot_detector#140]
There are two main ways to report players: In TF2 and in steam. Since we can't use the ingame report option, we could cheat and open the profile in a web browser in the background and use a similar like tampermonkey to report the bot. It is likely to have a bit of a performance impact and will probably be hard to implement, so this is just a suggestion.

**Comment by ParzivalWolfram** [comment]
You can still report people from within TF2...? (although this would be a good thing to make the detector do, if such is possible.)

**Comment by ClusterConsultant** [comment]
The we in this case is from the perspective of the tool. The tool itself cannot use the in-game option.

**Comment by ParzivalWolfram** [comment]
> The we in this case is from the perspective of the tool. The tool itself cannot use the in-game option.

My bad, I missed that.

**Comment by lnx00** [comment]
But this is most probably against Steam's TOS. Since there isn't an official way to report a player automatically (via Commands or API), they might not want you to do that.

**Comment by The-personified-devil** [comment]
I wouldn't use the automation with my main account, but it's probably dumb to implement.

**Comment by ClusterConsultant** [comment]
This is actually against steam subscriber agreement. 
"You may not use Cheats, automation software (bots), mods, hacks, or any other unauthorized third-party software, to modify or automate any Subscription Marketplace process" 
https://store.steampowered.com/subscriber_agreement/#4
Also reports are not used to actually ban accounts
