### ISSUE TITLE
Delete old log files

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/tf2_bot_detector#143]
We should delete log files if we have > 10 or we're over a few MB of logs.

**Comment by ParzivalWolfram** [comment]
I'd suggest making this configurable, as some logs may need saved and 10 logs under a few megs isn't that much, to be honest. Now, at like 100 logs, or >100MB? That might be worth something.

**Comment by PazerOP** [comment]
@ParzivalWolfram https://github.com/PazerOP/tf2_bot_detector/commit/4ca38c8652010ae44b2a241deeb88f22b28257fb deletes log files that are older than 1 week. Trying to avoid unnecessary complexity here by not adding a setting for this. Is this acceptable? I feel like 1 week is long enough to keep logs if someone needs to report a bug, otherwise they can copy logs out of the folder themselves.

**Comment by ParzivalWolfram** [comment]
That would probably be about right for most, yeah.
