### ISSUE TITLE
chat_english alternatives

### ISSUE THREAD

**Issue by JarateKing** [PazerOP/tf2_bot_detector#146]
An issue I've heard get brought up is that sometimes the `chat_english.txt` replacement process might screw up / miss the file and cause other mods' localization to not get loaded.

It might be worth just using a different file entirely that overrides the entries in `chat_english` entirely. `chat_english` was originally chosen for hud mods because it was fairly small file that would be easy to keep up to date, but that doesn't really matter too much if you are automatically generating the file -- there's nothing special about `chat_english` itself and there are many other localization files that can contain the relevant entries. And since `chat_english` is pretty much only used by huds and (afaik) no other localization files get regularly modded, using a different file to avoid collisions is a good approach imo.

For reference, the load order of files is as follows:
* replay_english
* youtube_english
* valve_english
* gameui_english
* valve_english (again)
* platform_english
* vgui_english
* tf_english
* chat_english
* tf_proto_obj_defs_english
* serverbrowser_english

Unfortunately I can't remember if earlier loads have priority over later loads, or later loads overwrite earlier loads. It should be pretty quick to test, just try it with one of the many early ones and with `serverbrowser_english` and see which one works.

**Comment by CrazyGunman2C4U** [comment]
That would fix my issue. Currently this app overwrites my entire custom 'translation' ingame.

Thank you JarateKing for contributing. Your work on teamfortress.tv is very valuable for HUD enthusiasts.

**Comment by PazerOP** [comment]
@CrazyGunman2C4U is your custom translation inside a VPK? The tool should be basing all of its modifications off of existing chat_english.txt/tf_english.txt files.

**Comment by PazerOP** [comment]
Also @JarateKing a few corrections, looks like `serverbrowser_english.txt` isn't loaded unless you open the server browser. Also, `closecaption_english.txt` is loaded between `chat_english.txt` and `tf_proto_obj_defs_english`.txt

**Comment by JarateKing** [comment]
Odd about `serverbrowser_english.txt`, I didn't verify that the strings were actively being used but it did show up in procmon when starting tf2 without doing anything special.

`closecaption_english.txt` is for captions rather than localization (despite the same naming convention) so it wouldn't be a valid option, I didn't mention it for that reason. It wouldn't be a good candidate anyway even if that weren't the case, since editing it is even more common than using custom chat_english in the first place.

**Comment by CrazyGunman2C4U** [comment]
@PazerOP No, it's inside a folder \tf\custom\<hud-name>\resource\chat_english.txt

I haven’t changed a thing since mentioning it in the discord chat.

**Comment by CrazyGunman2C4U** [comment]
The new method involving "closecaption_<language>.txt" seems to work well. This should fix any incompatibilities.
