### ISSUE TITLE
Grammar Mistake

### ISSUE THREAD

**Issue by TheBrunka** [PazerOP/tf2_bot_detector#156]
If only one cheater is on the opposing team, at the end of the message it's saying"Please kick _them_!".

**Comment by karlovchap** [comment]
Them works as singular too as a gender neutral, but is most often plural. I see no problem in this - should we say "Kick him"? I don't think so, _

**Comment by The-personified-devil** [comment]
It's correct grammar, please close this.

**Comment by PazerOP** [comment]
This is intentional, and as far as I'm aware it is correct grammar. What would suggest it say instead, @TheBrunka?

**Comment by TheBrunka** [comment]
Oh sorry then I'm just Hungarian and what I learned was that it was incorrect nvm

**Comment by TheBrunka** [comment]
> This is intentional, and as far as I'm aware it is correct grammar. What would suggest it say instead, @TheBrunka?

I don't know but maybe "Please kick the cheater!" and if there are multiple cheaters then "Please kick the cheaters!". But yes then it was my bad, sorry.😅
