### ISSUE TITLE
[Improvement] Auto-update

### ISSUE THREAD

**Issue by Haxorzz** [PazerOP/tf2_bot_detector#158]
It would be useful, not having to delete and redownload the tool and also it might help a bit with smartscreen? (Not 100% true)

**Comment by PazerOP** [comment]
I agree, with how frequently I end up pushing out updates, it would be beneficial to just have an "update now" button that does everything for you.

**Comment by Haxorzz** [comment]
Cool thanks :)

**Comment by PazerOP** [comment]
You should keep this issue open until the feature is released :)

**Comment by Haxorzz** [comment]
oh aight didnt know

**Comment by GolfinhoVoador** [comment]
Honestly, I think this one is worthy of releasing on 1.1...
It's getting pretty annoying to open TF2 Bot detector to a message "Update tf2 bot detector" but it still starts the game anyway...
Or you can make it so when that message pops up, the game wont start unless the user closes the pop-up.
