### ISSUE TITLE
Developer cvar forced on causes issues in Valve Competitive

### ISSUE THREAD

**Issue by cyberkitsune** [PazerOP/tf2_bot_detector#159]
TF2 Bot Detector forces `developer 1` which for some odd reason causes the console to overlay during game play in Valve Competitive only (for some reason)

as a viable usecase for bot detector is keeping casual bot free while waiting for comp queue, it may be a good idea to fix this at some point :)

Discussed in discord: https://discordapp.com/channels/716525494421553243/718612821973401650/734469332901429279

**Comment by samdisk11** [comment]
why not just switch developer to 0 when you are in a comp match?

**Comment by ClusterConsultant** [comment]
Last this was discussed in discord I think it was left at this might just be impossible due to how valve comp fucks with all kinds settings and cfgs.

**Comment by PazerOP** [comment]
> why not just switch developer to 0 when you are in a comp match?

`developer 1` needs to be set, then it needs to be locked by the usage of `alias developer`, which prevents the user or any config from ever changing this value again. This is to prevent configs from causing issues with the detector.

Normally, `contimes 0` also prevents the text from showing in the upper left corner, however `contimes` is not marked as a cvar that is acceptable to change during competitive mode, while `developer` is. So you get the ~8 lines of text in the top left in competitive modes.

I don't see any way to fix this, unfortunately.
