### ISSUE TITLE
The software is not launching

### ISSUE THREAD

**Issue by itistodaymydudes** [PazerOP/tf2_bot_detector#162]
I installed the bot detector because, as you all know, bots are annoying.

But whenever i try to run the software it comes up with the error "The code execution cannot proceed because tf2_bot_detector.dll was not found. Reinstalling the program may fix this problem" is there a fix for this?

**Comment by lnx00** [comment]
Install the bot detector according to this Guide: https://github.com/PazerOP/tf2_bot_detector#installation
Make sure to **extract all files** and not just run the tf2_bot_detector.exe from the zip file.

**Comment by itistodaymydudes** [comment]
i followed the site's instructions the first time i installed the software, and extracted every single file, and the software refuses to launch

**Comment by Domb-Loid** [comment]
Im also having the same issue. I extracted the whole .zip file and i get the same error message

**Comment by ClusterConsultant** [comment]
Can you please upload a screenshot of what files are in the extracted folder?

**Comment by itistodaymydudes** [comment]
![file](https://user-images.githubusercontent.com/68632537/88507063-667e1280-cf90-11ea-9087-9ec308823e91.png)

**Comment by PazerOP** [comment]
Looks like you downloaded the source code zip. As per https://github.com/PazerOP/tf2_bot_detector#installation, make sure to download [tf2_bot_detector_x64-windows_1.0.0.50.zip](https://github.com/PazerOP/tf2_bot_detector/releases/download/1.0.0.50/tf2_bot_detector_x64-windows_1.0.0.50.zip) or [tf2_bot_detector_x86-windows_1.0.0.50.zip](https://github.com/PazerOP/tf2_bot_detector/releases/download/1.0.0.50/tf2_bot_detector_x86-windows_1.0.0.50.zip), *not* the source code zip.

**Comment by itistodaymydudes** [comment]
thanks, its working now
