### ISSUE TITLE
Could this be adapted to work with other games?

### ISSUE THREAD

**Issue by CanadianJeff** [PazerOP/tf2_bot_detector#164]
Left 4 Dead 2?
CSGO?

**Comment by ClusterConsultant** [comment]
Potentially but I don't see the point. Definitely is out of scope of this project

**Comment by PazerOP** [comment]
Certain aspects of the tool could work on other games, but it's definitely not a priority, and not something I intend to spend time on. If someone else wanted to expand support though, they should be able to without too much work.

**Comment by CanadianJeff** [comment]
fair enough
