### ISSUE TITLE
debug report for "something is terribly wrong" type of error and odd Bot at same time

### ISSUE THREAD

**Issue by id-rotatcepS** [PazerOP/tf2_bot_detector#165]
I got votekicked immediately during a game where, by voicechat, a guy says something like "there's a bot on the server, please kick."  During the vote a screeching high pitched voicechat starts and I THINK that was a different account but I'm not sure.  I think one of them was "paramour" or maybe "peace of mind" in my log.
Anyhow when he announced that, I checked my detector, I had one account that I'd flagged as suspicious(? yellow) flashing and that's it.  I also noticed I had a "can't find the end of the chat, something is terribly wrong" type of message on the right side, so I started a debug report and about the same time is when I discovered I was the one he was voting off, so I didn't get a chance to mark either account or even verify my suspicious one was one of them before it all blanked out.

I feel like he started the voicechat/vote sequence as soon as he connected.
I feel like there was more than one account that was a problem at the time, but none were in the official list.

At the very least: the ability to mark player accounts after disconnecting (getting voted off) would be helpful.
[debug_report.zip](https://github.com/PazerOP/tf2_bot_detector/files/4970202/debug_report.zip)

Thanks!

**Comment by PazerOP** [comment]
Thanks for this, it was very helpful. I'm looking into it now.
