### ISSUE TITLE
What does Thirst means?

### ISSUE THREAD

**Issue by PabloDinella** [PazerOP/tf2_bot_detector#170]
First of all, thank you for this excellent tool! Hope I can contribute in some way someday.

But what does "Their Thirsty" means when I hover over a player's name? Couldn't find the meaning anywhere.

**Comment by 107zxz** [comment]
It means thats the number of times you've killed them / they've killed you.

**Comment by PazerOP** [comment]
@107zxz is correct, it is a ratio between the times you have killed them and the number of times they have killed you. It was added as a joke feature until I add a much more detailed stats panel, but I'm honestly probably going to remove it due to the amount of confusion it has generated.
