### ISSUE TITLE
Unable to use rcon with a tf2 instance opened with bot detector

### ISSUE THREAD

**Issue by ClusterConsultant** [PazerOP/tf2_bot_detector#172]
It is annoying to have to restart the game to use rcon on actual servers.

**Comment by PKPenguin321** [comment]
https://github.com/PazerOP/tf2_bot_detector/releases/tag/1.0.0.25
This is the latest release to not use RCON, it might be a good stopgap fix for you

**Comment by ClusterConsultant** [comment]
I am aware, I just use the standalone rcon client.

**Comment by PazerOP** [comment]
Its honestly probably a lot easier to just build an rcon client into the tool that defaults to pointing at the server you are currently connected to. Would that work?

**Comment by ClusterConsultant** [comment]
Not for my particular use case due to the number of aliases and binds I have to automate management. However, that may be useful for others. I think this issue overall is very very edge-case. This is probably one of the if not the lowest priority issue currently tracked.

**Comment by ClusterConsultant** [comment]
I'm going to close this since I don't think any effort should be put into it.
