### ISSUE TITLE
[Bug] DRP not working properly on community servers

### ISSUE THREAD

**Issue by lnx00** [PazerOP/tf2_bot_detector#173]
The new Discord Rich Presence is not working on many community servers.
While the bot detector is succesfully detecting the playerlist, it isn't showing any information in the rich presence.
It will just stay saying "Main Menu" most of the time. The weird thing is, that it will work somehow if you've been on a local server before joining a community server (But it'll still say "Local server" despite the fact that you're in an online server).

Community servers not working wasn't really important in the past. But it would be good, if the DRP would be working now.

**Comment by PazerOP** [comment]
Some community servers are running [plugins](https://forums.alliedmods.net/showthread.php?t=280233) that replace the output of the `status` command with a malformed version:
```
08/05/2020 - 23:16:49: hostname: Panda-Community.com #16 | 2Fort
08/05/2020 - 23:16:49: version : 5970214/24 5970214 secure
08/05/2020 - 23:16:49: upd/ip  :  193.192.59.191:27165 (public ip: 193.192.59.191)
```

This should be fixed as of 1c15cda968c9801950d54f68c9db12ad49ca1cef.
