### ISSUE TITLE
[Compile Error] Setting Discord Game SDK Values

### ISSUE THREAD

**Issue by AyeTSG** [PazerOP/tf2_bot_detector#175]
Hi! I'm wondering where exactly the ``DISCORD_CPP_GAME_SDK`` and ``DISCORD_GAME_SDK`` variables should be pointing to. When I set both of them to the directory where I have the SDK located, I get compile errors.

Where EXACTLY should I be pointing these values?

**Comment by AyeTSG** [comment]
This was fixed by installing the ``discord_game_sdk`` package via ``vcpkg``. I did some additional troubleshooting with @PazerOP over Discord, and he will be updating the compile guide, as it was out of date.

**Comment by PazerOP** [comment]
[The wiki](https://github.com/PazerOP/tf2_bot_detector/wiki/Compiling) has been updated to (hopefully) make things simpler. I'll look into switching the hardcoded vcpkg dependencies list to a response file that both CI and the script on the wiki can use, so they never get out of sync again.
