### ISSUE TITLE
Hacking bot suggestions

### ISSUE THREAD

**Issue by blastoise33** [PazerOP/tf2_bot_detector#182]
Can we make a list so people can suggest bots they know or suspect are hacking?

This one I'm pretty sure it might be in your list already.
https://steamcommunity.com/profiles/76561199063230386/

These ones are suspect I'm not 100% sure though.
https://steamcommunity.com/profiles/76561199039636814/
https://steamcommunity.com/profiles/76561199080505060/
https://steamcommunity.com/profiles/76561199067779014/
https://steamcommunity.com/profiles/76561199064273004/
https://steamcommunity.com/profiles/76561199067751578/
https://steamcommunity.com/profiles/76561199065394772/
https://steamcommunity.com/profiles/76561199067791761/

Theres also new hacking bots that come on in the last few days with no name and 1 ping.

**Comment by PazerOP** [comment]
The first one would already be detected ingame if it was using "[g0tb0t]" in its name. 

Unfortunately, while the rest of these do seem likely to be bots, I cannot accept user submissions to the official list. It would be too open to abuse from false reports.
