### ISSUE TITLE
Finalize Steam API Integration

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/tf2_bot_detector#184]
The player name lookup has already existed for some time and is tested (well enough).

- [x] Add a textbox to settings (b21fc019ed2378fe2068ddae936a4f373171a623)
- [x] Add the other relevant info from the `GetPlayerSummaries` endpoint to the scoreboard tooltip
- [x] Fill out https://github.com/PazerOP/tf2_bot_detector/wiki/Integrations:-Steam-API
- [x] Tooltip: Show VAC bans
- [x] Tooltip: Show TF2 playtime
- [x] Highlight: Show friends

**Comment by Czechball** [comment]
Hey! I really like where this is going. However, I think that there's room for improvement. My suggestions are based on this image you posted on Discord:
![A screenshot](https://media.discordapp.net/attachments/716525494861824042/742577612265750629/unknown.png)

- Remove Comment Permissions - I don't really see a purpose here
- Instead; add TF2 playtime (if public) using the `IPlayerService/GetOwnedGames` API call
- Add a check if the given person is on your friend list - this can be done using `ISteamUser/GetFriendList` (if public) and highlight them (purely cosmetic, won't prevent any auto-marks)
- A flag icon with the person's country (if public) (part of the `GetPlayerSummaries` call)
- List VAC bans (`ISteamUser/GetPlayerBans`)

Also, I am aware of the problem that some API calls can accept multiple SteamIDs and some can only accept a single one. This could be solved by only sending the API request and storing the data if a user hovers over the player (for the single SteamID calls).

**Comment by PazerOP** [comment]
* I agree that comment permissions are probably not useful to know.
* TF2 playtime seems a good idea. 
* Should be easier to just check your own friends list (since it is using your account's API key, you always have access)
* Icons of any sort are probably not going to be a thing for a while. I don't have a good way to render them.
* VAC bans are also a good idea IMO.

**Comment by Czechball** [comment]
Thanks for the reply. While icons may not be possible, I think that country indicator would be a nice thing nonetheless, even a text one

**Comment by ClusterConsultant** [comment]
This seems stable and useful. I'm going to mark this as done for now.

**Comment by Barmem** [comment]
what about country indicator?
