### ISSUE TITLE
High Latency After Roughly 30 Minutes

### ISSUE THREAD

**Issue by The-Officer-DWm** [PazerOP/tf2_bot_detector#188]
First off you're doing God's work with this tool, thank you!

I am getting an issue where after about 30 Minutes of playing in a match, my ping reaches a very constant 150-200 ms, and Soldier becomes the class you can hit anything with.  This happens on even the closest official servers to me, Virginia, which I normally get 30-70 ms.  I don't know what exactly causes this obviously, but all I know is that ping response is high with the tool running, and the game runs fine without it.  If you wan't me to try my hardest to get more details, I absolutely will.  Thanks.

**Comment by PazerOP** [comment]
Does the issue resolve itself if you close the tool while this is happening?

**Comment by The-Officer-DWm** [comment]
Will check later today and edit this comment.

**Comment by The-Officer-DWm** [comment]
Sorry about the late response, but sadly, no, there is still latency.

**Comment by PazerOP** [comment]
Could you post a screenshot of what your `net_graph 5` looks like when this is happening?

**Comment by The-Officer-DWm** [comment]
Hi, very very sorry to "necro" this, but after a few months of on and off research with tracert, ping, and so much more, I have found out that this is not n relation to the program, but rather something above and beyond my control, and sadly something that may never be fixed on my end.  Long story short, somewhere down the pipeline of a packet going to Valve's game servers, there are a few suspect IP addresses that respond to tracert with an inexplicably high latency, and directing pining results in my ISPs servers sending back a message that indicated the IP address doesn't exist.  For some reason, the ISP plays a bit of RNG with me, sometimes deciding to the the broken route, and sometimes taking the not broken route at the expense of a single extra passthrough point.  I am very sorry I never did more research into this before hand, and it also kills me that as an end user, this unique issue to me will fall on deaf ears to my ISP.  Thank you for taking your time to respond, and thank you for keeping TF2 fun and enjoyable.

**Comment by ClusterConsultant** [comment]
Thank you for updating this. Don't fear "necroing." We would rather hear from you then close an issue for inactivity. We appreciate your kind words and support.
