### ISSUE TITLE
Failed to initialize Discord Game SDK: Result::InternalError

### ISSUE THREAD

**Issue by PKPenguin321** [PazerOP/tf2_bot_detector#192]
On release 1.1.0.10

The error `Failed to initialize Discord Game SDK: Result::InternalError` repeats every 10 seconds after launching the game through the tool.
![image](https://user-images.githubusercontent.com/8345184/90949150-dac69d00-e3fa-11ea-8072-e26dc903a329.png)
Discord is running as administrator, and I have Discord set to not report what I am currently playing.

**Comment by ClusterConsultant** [comment]
Since this is an upstream issue that can be safely ignored I'm going to close this

**Comment by guarunaut** [comment]
I'm having right now
