### ISSUE TITLE
False positives stemming from myg0t chat rule

### ISSUE THREAD

**Issue by wildyaboku** [PazerOP/tf2_bot_detector#197]
Hi. I'm running a similar program and am getting marked as a cheater by TF2BD when calling out myg0t bots, due to this rule:

```json
"chatmsg_text_match": {
	"case_sensitive": false,
	"mode": "contains",
	"patterns": [
		"myg0t.gg"
	]
},
```

Example of what happens in chat:

```
[redacted] :  Attention! There is a cheater on the other team named irc.myg0t.gg:6667#myg0t. Please kick them!
[me] :  There is still a cheater named “irc.myg0t.gg:6667#myg0t” on RED!
[redacted] :  Attention! There are 2 cheaters on the other team named [me], irc.myg0t.gg:6667#myg0t. Please kick them!
```

I ask that you reconsider this chat rule – it will produce false positives when typing out myg0t's full name or pasting it into chat.

**Comment by ClusterConsultant** [comment]
This rule is a bit useless these days.

**Comment by Czechball** [comment]
Which version of TF2BD are you using?

**Comment by ClusterConsultant** [comment]
This rule is present in the most recent build.

**Comment by wildyaboku** [comment]
Skimming over the code, it seems that it saves these detections to a local file. Is that correct? Is it safe to assume I won't be able to play with the two users who "detected" me again?

Just my two cents, but I don't think this type of logic should be necessary:
https://github.com/PazerOP/tf2_bot_detector/blob/master/tf2_bot_detector/ModeratorLogic.cpp#L213

Also for clarification: @Czechball I'm not using TF2BD. It's other players using it who incorrectly mark me as a cheater.
