### ISSUE TITLE
Add rule for new bot called @everyone 

### ISSUE THREAD

**Issue by ShaneDawsonsCat** [PazerOP/tf2_bot_detector#199]
New bot named @everyone in game. supposedly hosted by poohook.

**Comment by ClusterConsultant** [comment]
Does the name contain any illegal characters?

**Comment by ShaneDawsonsCat** [comment]
No, the @everyone bots do not contain any illegal characters. that is their full name. @everyone .

**Comment by ClusterConsultant** [comment]
I have a feeling that is too generic of a name to create a hard rule for. I'll leave the digression to others

**Comment by CrazyGunman2C4U** [comment]
Why would they name the bots @everyone? I've read somewhere that people can trigger bot hosters as the logs will forward @everyone to their discord/telegram, notifying them.

But how will they notify random users who don't relay the logs?

Either another dumb name, or not a real bot.

Or:
Might also be related to https://old.reddit.com/r/TF2hackerSWAT/comments/ig4i50/lemme_do_a_lil_magic_trick_for_yall_real_quick_as/

```
@Breadgineer

<@everyone>

@Deputy

@deleted-role

@Major

\@everyone

u/everyone
```

Do they want to harass people posting patrol results using @everyone who don't even have that permission??

**Comment by The-personified-devil** [comment]
> Why would they name the bots @everyone? I've read somewhere that people can trigger bot hosters as the logs will forward @everyone to their discord/telegram, notifying them.

Could you please explain what you wrote, because I don't understand it?
Thanks in advance

**Comment by CrazyGunman2C4U** [comment]
@The-personified-devil 
Quote from comedy man on a very serious discord server..

```
whenever a discord bot joins
once they properly join say @ everyone
this will ping everyone in the catbot server
really pisses them off
they've said it themself
```

I assume that they either want to ping (notification -> annoying) everyone (using a chat platform) or cause confusion (they certainly did).

**Comment by ClusterConsultant** [comment]
These bots don't seem to be prevalent at this time. Closing for now.
