### ISSUE TITLE
Shasta Bots arent detected as cheaters

### ISSUE THREAD

**Issue by Ignited550** [PazerOP/tf2_bot_detector#212]
**PLEASE** in the new update detect Shasta bots as cheaters using their username (steam name, not in-game name) because they spam chat and aimbot and it's so annoying

**Comment by ClusterConsultant** [comment]
I think this may no longer be relevant

**Comment by ClusterConsultant** [comment]
This issue will be closed on 25/01/2021 if nothing more is heard
