### ISSUE TITLE
Resizing subwindows 

### ISSUE THREAD

**Issue by Barmem** [PazerOP/tf2_bot_detector#214]
you can drag blue line left and right, but you cant drag red up and down, i dont think people need that much space taken by console outputs 
![изображение](https://user-images.githubusercontent.com/70278808/94976357-94ef0f80-0536-11eb-87c0-289e5e6c0592.png)

**Comment by Barmem** [comment]
i would even switch player list and chat with each other

**Comment by PazerOP** [comment]
@Barmem is it sufficient to just have it automatically resize to fit all the scoreboard rows? Or did you really want to be able to drag it yourself? Being able to drag it yourself is much more difficult, since ImGui doesn't support this functionality out of the box, as far as I'm aware.

**Comment by Barmem** [comment]
i think switching chat and playerlist is good enough.
