### ISSUE TITLE
New catbot names evade detection.

### ISSUE THREAD

**Issue by VigilantBag** [PazerOP/tf2_bot_detector#219]
It seems catbot has implemented new names which would help them evade detection by including invisible unicode characters. The image below is a list of names I was able to capture.
Note: The characters are NOT visible in game or via steam community, only when processed by the program. These bots still wear all three hat cosmetics as well.
https://skyportal.xyz/FABdVtuxyflBd5AN-J_zYtj8LWcmC0as1HUwO3k8wWNbYA

**Comment by ClusterConsultant** [comment]
Official rules have been updated, for further detection robustness see #218
