### ISSUE TITLE
New "matchroom.live/snooker" bots.

### ISSUE THREAD

**Issue by Ploudo** [PazerOP/tf2_bot_detector#223]
These bots all have the same name, and when multiples join, they add a (1), (2), (n)... in front of the name in brackets in the title. They disconnect after enough people vote yes on a kick but have left before the server can initiate a kick. This lets them freely join as they haven't been banned from the server.
![20201029023154_1](https://user-images.githubusercontent.com/17126689/97514602-6aef0880-198f-11eb-952a-c6e7b1deeb33.jpg)

These bots have mostly been plaguing EU servers as far as I know.

**Comment by cyrusParvereshi** [comment]
I think sometimes a bot leaves before they can get banned too, right? Then the vote always fails and they can come back.

**Comment by 107zxz** [comment]
> 
> 
> I think sometimes a bot leaves before they can get banned too, right? Then the vote always fails and they can come back.

Patched by valve 6 months ago

**Comment by ClusterConsultant** [comment]
Is this still relevant? These bots no longer seem to be active
