### ISSUE TITLE
Chat completely broken

### ISSUE THREAD

**Issue by MrDrProfMan** [PazerOP/tf2_bot_detector#226]
The new 1.1.0.639 version has completely broken my chat. I could not see my own or other peoples messages and I have no idea what part of the program is causing it.

**Comment by ClusterConsultant** [comment]
Can you please provide us with your debug report? You will likely also receive faster support in the discord since more people are active there.

**Comment by MrDrProfMan** [comment]
[debug_report.zip](https://github.com/PazerOP/tf2_bot_detector/files/5473676/debug_report.zip)
This is the debug report, hope it helps's. The bug also seems to only happen in casual. Everything seemed to be normal in community servers.

**Comment by ClusterConsultant** [comment]
Do you have a premium account?

**Comment by MrDrProfMan** [comment]
I do have a premium account. I also thought for a while that I might still be free to play, but in Steam it says I have the "premium dlc".

**Comment by ClusterConsultant** [comment]
In TF2 Steam properties under the language tab is it set to your preferred language?

**Comment by MrDrProfMan** [comment]
Well I just went on the discord and downloaded 1.1.0.674 and it fixed the issue. I'm sorry for wasting your time.

**Comment by ClusterConsultant** [comment]
That's my bad. Didn't even comprehend that 639 < 674. I can recommend the installed version with auto updating btw. I'm glad it's working for you now
