### ISSUE TITLE
Failed to get TF2 command line arguments

### ISSUE THREAD

**Issue by Picklejar05** [PazerOP/tf2_bot_detector#230]
I've been trying to figure this out since I downloaded this a few days ago. I was able to launch TF2 with bot detector once, and the whenever I launched bot detector afterwards it would show this:

![image](https://user-images.githubusercontent.com/50224374/99599474-4eebef00-29b0-11eb-92da-efb8e76bf40b.png)

I've looked in the properties of hl2.exe and steam.exe, and neither of them are set to launch as administrator. I've tried relaunching steam, and that didn't work. When I try launching bot detector as admin, it shows this (TF2 is not running):

![image](https://user-images.githubusercontent.com/50224374/99599658-a68a5a80-29b0-11eb-91ad-5e5516596aa3.png)

I also looked up the console options that it is showing, and it looks like these are all server commands. I tried adding them with the correct information anyway, but it didn't even notice when I relaunched bot detector. I'm using v1.1.0.674, downloaded from the MS store, and my OS is Windows 10 64 bit, the latest steam client, and the latest version of TF2.

## software versions

![image](https://user-images.githubusercontent.com/50224374/99600412-3d0b4b80-29b2-11eb-8b10-d138772ba18f.png)
![image](https://user-images.githubusercontent.com/50224374/99600449-4eecee80-29b2-11eb-9adb-bdccfc196a0a.png)
![image](https://user-images.githubusercontent.com/50224374/99600809-04b83d00-29b3-11eb-86d1-9effade0c5d5.png)
![image](https://user-images.githubusercontent.com/50224374/99600884-24e7fc00-29b3-11eb-8b9c-ba1b9628156b.png)

**Comment by cyrusParvereshi** [comment]
Did you try to uninstall/reinstall tf2 and/or tf2 bot detector and then verify integrity of game files?

**Comment by Picklejar05** [comment]
I have tried reinstalling bot detector and verifying game files, I’ll need
to try reinstalling tf2 though.

**Comment by Picklejar05** [comment]
it looks like verifying game files again fixed it. Thanks!
