### ISSUE TITLE
Warning message for when the bot kicks you. 

### ISSUE THREAD

**Issue by peruna77** [PazerOP/tf2_bot_detector#239]
The newest catbots instantly autokick the player they stole a name from - faster than TFBD can kick the bot.

I suggest adding a chat bind that is sent when someone with a similar name to yours tries to kick you. Everyone is too quick to press F1 on any cheating vote so there is not much time to react with a manual message.

If checking for name similarity is difficult, alternatively the bind could be activated when the kicker has a different steam name than the ingame name.

PS: Awesome work overall pazer!

**Comment by ClusterConsultant** [comment]
This has similar technical challenges as #168 

I.E. there is no console output for votes so its impossible to know when a vote is called, who the vote is called on, who called the vote, or the status of any existing vote. This would likely have to wait until demo parsing and even then there would be some significant delay.

**Comment by ClusterConsultant** [comment]
This also fits in with the theme of #189

**Comment by GolfinhoVoador** [comment]
Is there even a command to change your exit message? I mean, I know bots can do it, but can humans do that too?

**Comment by ClusterConsultant** [comment]
No, its impossible without injecting into tf2 and doing nefarious things

**Comment by PazerOP** [comment]
The above is correct, this unfortunately isn't possible.

**Comment by PazerOP** [comment]
> 
> 
> This has similar technical challenges as #168
> 
> I.E. there is no console output for votes so its impossible to know when a vote is called, who the vote is called on, who called the vote, or the status of any existing vote. This would likely have to wait until demo parsing and even then there would be some significant delay.

This is correct, unfortunately this feature isn't possible.
