### ISSUE TITLE
[BUG] Pressing next on "Steam must be open to use tf2 Bot Detector" with steam open does nothing.

### ISSUE THREAD

**Issue by GolfinhoVoador** [PazerOP/tf2_bot_detector#245]
**Describe the bug**
> Instead of tf2 bot detector starting, It does nothing.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Open tf2 bot detector
> 2. Click on "Next >"

**Expected behavior**
> Tf2 Bot Detector opens tf2 and starts as usual.

**Logs**
> [17:19:35] Filesystem.cpp(129):ResolvePath: ResolvePath("cfg/settings.json", PathUsage::Write) -> "D:\TF2 BOT DETECTOR\\cfg/settings.json"
> [17:19:35] WorldState.cpp(292):UpdateFriends: Failed to access friends list (our friends list is private/friends only, and the Steam API is bugged)
> [17:19:35] Processes.cpp(229):IsSteamRunning: Failed to enumerate processes: system:24

**Desktop (please complete the following information):**
> - OS: Windows 10
> - 1.1.0.749 (loose files)

**Additional context**
> I modified the path on the logs*

https://user-images.githubusercontent.com/50271451/103695276-08ac1880-4f7b-11eb-9a1f-35f8c3aab14c.mp4

**Comment by ClusterConsultant** [comment]
I am also experiencing this

**Comment by ClusterConsultant** [comment]
Upgrading to critical on account that this completely prevents the tool from functioning

**Comment by ClusterConsultant** [comment]
some rapid testing has revealed that closing tf2bd, then steam, reopening steam, then tf2bd, resolves this issue. Its a workaround but its not a good one

**Comment by GolfinhoVoador** [comment]
> some rapid testing has revealed that closing tf2bd, then steam, reopening steam, then tf2bd, resolves this issue. Its a workaround but its not a good one

That didn't work for me.

**Comment by ClusterConsultant** [comment]
Hm, this generally seems to be having inconsistent issues. Sometimes it works, sometimes it doesn't. Right now I would advise downgrading to previous nightly. As is the life of nightly builds.

**Comment by ClusterConsultant** [comment]
This is my debug report. It should encompass one failure, one success, and one weird in between event where it displayed the behavior in question then reconnected to the existing tf2 instance.
[debug_report.zip](https://github.com/PazerOP/tf2_bot_detector/files/5772478/debug_report.zip)

**Comment by PazerOP** [comment]
Supposedly fixed in https://github.com/PazerOP/tf2_bot_detector/commit/106860c10c85a0521373d3b5b8b4b70489ec68b4

**Comment by GolfinhoVoador** [comment]
> Very latest build seems to resolve this. Give it a shot when possible



> Supposedly fixed in [106860c](https://github.com/PazerOP/tf2_bot_detector/commit/106860c10c85a0521373d3b5b8b4b70489ec68b4)

Fixed!
