### ISSUE TITLE
[BUG] MSIX Install Link Failure

### ISSUE THREAD

**Issue by ClusterConsultant** [PazerOP/tf2_bot_detector#250]
**Describe the bug**
New installations using the "one click" install link are nonfunctional due to settings.json not existing. This has been reproducible on 1.1.0.753

**To Reproduce**
1. On a fresh Win 10 instance, use the one click link to install
2. Error: 

![](https://i.imgur.com/TGOgFSx.png)

**Additional context**
Underlying issue has been identified and a fix is in progress. Due to its nature, this is added to 1.2 requirements.

**Comment by PazerOP** [comment]
Fixed in f8e87b3156e78664650c47795dafddd3a25fe379.
