### ISSUE TITLE
[BUG] can't start tbd on win7: "Failed to initialize filesystem"

### ISSUE THREAD

**Issue by kotc** [PazerOP/tf2_bot_detector#265]
**Describe the bug**
1.1.0.769 can't start in win7 sp1 x64

error box says:
unhandled exception
failed to initialize filesystem
exception type: class std::system_error
exception message: windows.cpp(84):operator (): failed to find function GetCurrentPackageFamilyName in Kernel32.dll: the specified procedure could not be found.
exception source filename: ..\tf2_bot_detector\Filesystem.cpp:129
exception source function: Init

**To Reproduce**
1/ download tf2-bot-detector_x64-windows_1.1.0.769_Release.zip
2/ unpack
3/ run tf2_bot_detector.exe

**Expected behavior**
program starting ok

**Screenshots**

**Additional context**
vc++ is the latest version downloaded and installed along with release

**Comment by kotc** [comment]
![tbd-crash-win7](https://user-images.githubusercontent.com/10637309/104607333-a1781d80-5678-11eb-9ecc-9e8ca40f4512.png)

**Comment by ClusterConsultant** [comment]
What version of windows are you on?

**Comment by kotc** [comment]
yes, windows 7 sp1, without updates due to lack of drive space

**Comment by kotc** [comment]
but if i read the page correctly:

https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentpackagefamilyname

that function is win8+ anyway?

**Comment by ClusterConsultant** [comment]
Yes, there was some effort to extend our support of windows 7 somewhat but I don't think sp1 was taken into consideration. Best bet would be to downgrade and wait for @PazerOP's response.

**Comment by kotc** [comment]
yup, no such function in win7

https://stackoverflow.com/questions/52207484/determine-if-c-application-is-running-as-a-uwp-app-with-legacy-support

**Comment by PazerOP** [comment]
@kotc Give the latest nightly (794) a try when you have a chance.

**Comment by kotc** [comment]
it started, tf2 launched. seems to work, thank you! (i didnt try connecting to valve servers, only practice, getting late here :)

**Comment by PazerOP** [comment]
Great to hear. I'm marking this as closed in c182fc7d1f46cb7bb2745cba4ce03cf145bd58b8. Please make another comment or open another issue if you run into any other issues.
