### ISSUE TITLE
Auto-leave

### ISSUE THREAD

**Issue by Barmem** [PazerOP/tf2_bot_detector#277]
There should be an option for automatically leaving while joining the server if tool detects more that N cheaters on server. Even if auto requeue is not possible auto disconnect or canceling loading into server should be possible.

**Comment by brachistosaurus** [comment]
Although `disconnect` exists, I doesn't cancel your "connection" to the server and will try to force you back in. So, I don't think it's possible.

**Comment by ClusterConsultant** [comment]
This was discussed a while ago. 

It is impossible.
