### ISSUE TITLE
Make the tool's window remember its size and position across launches

### ISSUE THREAD

**Issue by Kenajcrap** [PazerOP/tf2_bot_detector#278]
**A clear and concise description of what the problem is.**
Every time I start the program I need to resize and move the window to my second monitor, this is not a big annoyance or anything, but can be improved.

**Describe the solution you'd like**
Make the tool remember its window size and placement like many other programs do

**Describe alternatives you've considered**
If "making it remember" entails the creation of a config file or is somehow not worth it for such a small QOL improvement, creating a setting akin to cmd's where you can manually save the default window size and placement would also suffice.

**Comment by brachistosaurus** [comment]
Also, seems related to the closed issue of #102.

**Comment by ClusterConsultant** [comment]
#102 was closed due to cleanup rather than a true close.

**Comment by ClusterConsultant** [comment]
Someone just pointed out that this is basically the same as #213 so I'm going to move it over there. I do however prefer how @Kenajcrap worded it more, so good job on that
