### ISSUE TITLE
Respect Votekick Cooldown

### ISSUE THREAD

**Issue by zalawi** [PazerOP/tf2_bot_detector#279]
After the bot detector calls a votekick, there may still be bots on the player's team - either because there aren't other players on the team with the bot detector calling a votekick or because the bot survived the votekick.  The bot detector still tries to call votekicks, however, even though a vote cooldown may be preventing a votekick from being succesfully.

The result is a continuing popup blocking part of the screen, along with a failure sound effect, both of which make the player's life harder, for no discernible benefit.

After an auto-votekick is called, the bot detector should refrain from calling votekicks again until either the server has been changed (clearing the cooldown) or a certain amount of time has passed (perhaps configurable, but defaulting to the value on TF2 casual servers, which I believe is 2 minutes).

In addition, it may be helpful to automatically broadcast a message in teamchat to prompt other teammates to kick the bot (much like the program broadcasts a message in normal chat when the enemy team has a bot), including an explanation that the current player's votekick is on cooldown, so they can't call the vote themselves.  Perhaps some logic can be used to ensure this doesn't happen in the first few seconds of votekick cooldown, so that it doesn't prompt unnecessary spam in the event that another player's Tf2 Bot Detector is just about to call a votekick.

**Comment by ClusterConsultant** [comment]
This has been resolved somewhat in a recent build. There is an experimental timer. Glitches are still being worked out and its not super reliable yet due to how little information is presented to console about vote status.
