### ISSUE TITLE
Integrate Steam Library Launch Options

### ISSUE THREAD

**Issue by HollyBlocky** [PazerOP/tf2_bot_detector#280]
It appears that the launch options in your steam library do not carry over to launching TF2 from the bot detector, though this needs to be confirmed because I could be incorrect. Kinda bugs me because I have frame-saving launch options that make the game more playable (e.g -threads 8, -noipx, etc.) and I am unsure if that carries over.

I'm not sure how difficult it is, but I was wondering if it wasn't too much of a bother to integrate Steam Launch Options to the Bot Detector (if not already).

An alternative could be allowing standalone launch options for the Bot Detector's TF2 shortcut.

Notes:
-issue has not been confirmed
-issue may need to be looked into

![steamwebhelper_pwuWgGjcG5](https://user-images.githubusercontent.com/78760703/107276631-522bcf80-6a21-11eb-9d85-93d6c33f8f75.png)

**Comment by HollyBlocky** [comment]
If someone would like to confirm this, please do so.

**Comment by moebkun** [comment]
-threads 8 does nothing. TF2 is still capped at 3 afaik

**Comment by PazerOP** [comment]
-noipx also does not appear to exist anywhere in the code

**Comment by andy013** [comment]
I think this already works. At least when I quickly tested it with the -novid launch option it seems to work as expected.

**Comment by ClusterConsultant** [comment]
I am unable to reproduce this. Can you make absolutely sure you are having this issue by using weird resolutions or `-console` or `-novid` or some other very obvious flag?

**Comment by PazerOP** [comment]
I am still unable to reproduce this, and @HollyBlocky has not replied with any additional info. Myself (and I imagine many others) have all sorts of obvious things on the command line (like `-novid`), that we would immediately notice if they were missing.

If anyone is still experiencing this problem, please leave a comment and this issue will be re-opened.
