### ISSUE TITLE
So I got an idea

### ISSUE THREAD

**Issue by Blah13225** [PazerOP/tf2_bot_detector#287]
I don't know if this would go here or somewhere else but if possible could you make it so you could see the status of each person in the tab menu of tf2 and change their statuses I just want to be able to easily do that

**Comment by brachistosaurus** [comment]
In other words, you want the functionality of the detector's scoreboard to be part of TF2's scoreboard?

**Comment by Blah13225** [comment]
yes

**Comment by ALT-F-X** [comment]
No

**Comment by ClusterConsultant** [comment]
This is not possible. For something similar see #262
