### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JackAttacktl** [PazerOP/tf2_bot_detector#290]
**Describe the bug**
> A clear and concise description of what the bug is.
A file didn't come with the .ZIP
**To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to 'The file location'
> 2. Click on 'The executable'
> 3. Scroll down to 'Its a popup'
> 4. See error
The code execution cannot proceed because MSVCP140_ATOMIC_WAIT.dll was not found. Reinstalling the program may fix this problem.
**Expected behavior**
> A clear and concise description of what you expected to happen.
I expected it to open up the main menu.
**Logs**
> Add any relevant logs. Logs are found by going to File → Open Logs Folder

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
> - OS: [Windows 10]
> - Version of bot detector [latest]

**Additional context**
> Add any other context about the problem here.

**Comment by JackAttacktl** [comment]
I redownloaded the ZIP two times, its just not there.

**Comment by PazerOP** [comment]
You are missing the latest Visual C++ Redistributable: https://aka.ms/vs/16/release/vc_redist.x64.exe
