### ISSUE TITLE
Download an update, without having Steam open.

### ISSUE THREAD

**Issue by brachistosaurus** [PazerOP/tf2_bot_detector#291]
**Why?**

Since updating the program doesn't rely on Steam, there's no reason to require opening it (before requesting an update).

-----

Before opening Steam:
![1](https://user-images.githubusercontent.com/77030765/108926561-abdcee00-760c-11eb-8dc7-38ddd7249107.png)

After opening Steam:
![2](https://user-images.githubusercontent.com/77030765/108926562-ac758480-760c-11eb-80a3-b816c550f9f0.png)

**Comment by ClusterConsultant** [comment]
Is there a use case for updating the tool without wanting to use it?
