### ISSUE TITLE
add options to minimize console spam

### ISSUE THREAD

**Issue by kotc** [PazerOP/tf2_bot_detector#293]
**A clear and concise description of what the problem is.**
> Ex. I'm always frustrated when [...] i try to see what's on console but it's spammed with ping lists etc (and as such i dont use them)

**Describe the solution you'd like**
> add options in TBD that quiet things it sends to console

**Additional context**
> please consider the above, because otherwise console is almost unusable with TBD running, unless it's essential and cant be disabled without losing functionality of TBD when it comes to detect/kick bots

**Comment by ClusterConsultant** [comment]
It is required for functionality. You can use scroll lock to prevent your console from being dragged down. #161
