### ISSUE TITLE
Auto close messed up -hijack instances

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/tf2_bot_detector#30]
Sometimes the main game "declines" to process the -hijack command arguments. This causes the -hijack instance to display a popup. If the -hijack instance lives for more than 5 seconds or so, we should just force quit it.

Also don't let more than one instance of hl2.exe be running at once... 
![image](https://user-images.githubusercontent.com/6569500/83929338-dcf85400-a747-11ea-98ec-34120809a3e7.png)
(from discord user Бармен#7002)

**Comment by The-personified-devil** [comment]
Please close, you solved it with local rcon. Thanks

**Comment by ClusterConsultant** [comment]
Already fixed with 5 second timeout. Will be super fixed with release of rcon
