### ISSUE TITLE
[BUG] new aaaaaa_votefailed_eraser folder being created on every start

### ISSUE THREAD

**Issue by SammCheese** [PazerOP/tf2_bot_detector#301]
**Describe the bug**
>Every Start, a New aaaaaaaaa_votefailed_eraser folder created

**To Reproduce**
> Open custom folder
> Start TF2 Bot Detector Nightly 
> See More Felders being Created

**Expected behavior**
> A single aaaaaaaaa_votefailed_eraser folder

**Screenshots**
> 
![image](https://user-images.githubusercontent.com/52699291/110748328-dbf8d380-823f-11eb-8f93-b5851016d4a0.png)

**Desktop (please complete the following information):**
> - WIndows 10
> - TF2 Bot Detector v1.2.0.910

**Comment by PazerOP** [comment]
Thanks for reporting this. Try updating to >= 918, manually delete those folders, and then see if they are still being created. 

This issue will be closed in ~1 week if nobody else notices issues.

**Comment by SammCheese** [comment]
Versions >=918 Now remove the Folder on Close

Closing Issue
