### ISSUE TITLE
Custom chat warning messages

### ISSUE THREAD

**Issue by TheMikirog** [PazerOP/tf2_bot_detector#303]
**A clear and concise description of what the problem is.**
Because bots are starting to catch onto the existence of the tool, they start to spam fake warning messages as a means to spread confusion. This means that legitimate users can get blamed by other users as potential cheaters or trolls for just using the detector's chat warning messages.

**Describe the solution you'd like**
In my opinion being able to customize the warning message should sidestep the issue of people mistaking the warning as a bind. This way it can be personalized while still retaining its power of informing people.

**Describe alternatives you've considered**
If a bot is on the other team, the chat message seems to be the only way to inform them about the threat and I couldn't find any other ways of informing people in a less intrusive manner.

**Additional context**
My day to day use of the tool made people blame me for spamming binds, trolling or worse being a cheater myself despite meaning no ill will, since bots started to use the chat warning aswell.

**Comment by ClusterConsultant** [comment]
#70
