### ISSUE TITLE
FaceIT AntiCheat Warning

### ISSUE THREAD

**Issue by owenwastaken** [PazerOP/tf2_bot_detector#307]
**A clear and concise description of what the problem is.**

When using Faceit's community servers, they require you to install and run an anti-cheat that blocks the ability for TF2 Bot Detector to communicate with TF2

**Describe the solution you'd like**

TF2 Bot Detector should check to see if Faceit's anti-cheat is running when the program starts and will let the player know that they should close the anti-cheat.

**Comment by ClusterConsultant** [comment]
Is face it still a thing that people play?

**Comment by owenwastaken** [comment]
FaceIt is still alive and well. And probably will be until Valve completely fixes the bot issues
