### ISSUE TITLE
New bot evolution

### ISSUE THREAD

**Issue by GamerD4rker** [PazerOP/tf2_bot_detector#308]
Hello! I am here to communicate that there's new fake anti-bots that are making people up-set about the use of TF2 Bot Detector so much that people just try to kick users of this program
I'm gonna also send the chat logs in case of need any info
Quick reminder what makes the difference between an anti-bot and a fake anti-bot is that they don't show up who sent the message instead they hide their name claiming that in the other team there's a bot while probably playing music on the background
![12173858 325000001_image](https://user-images.githubusercontent.com/75317531/112855064-60ec4580-90a6-11eb-99a9-522219ed7026.png)

**Comment by ClusterConsultant** [comment]
this has been known for a while. there is not much we can do about it.
