### ISSUE TITLE
[BUG] ♥ detecting as name-stealer

### ISSUE THREAD

**Issue by ByThePowerOfScience** [PazerOP/tf2_bot_detector#319]
**Describe the bug**
False positive for https://steamcommunity.com/profiles/76561199019626572 due to heart Unicode character.  The heart is visible in-game, so it can't be used by name-stealers.

**To Reproduce**
Have someone with the heart character in their name join, and they'll be picked up as a cheater by the tool.

**Expected behavior**
The player should not be marked as a cheater.

**Logs**
`ModeratorLogic.cpp(171):OnRuleMatch: Marked [U:1:1189264453] with Cheater due to rule match with "Generic name-stealing bot"`

**Desktop (please complete the following information):**
> - OS: Windows 10
> - Version of bot detector [e.g. 1.1.0.674] v1.2.0.798

**Comment by ClusterConsultant** [comment]
'♥' (BLACK HEART SUIT, U+2665) does not match any rules.

'‏' (RIGHT-TO-LEFT MARK, U+200F) and '‬' (POP DIRECTIONAL FORMATTING, U+202C) are the only symbols used for the "Generic name-stealing bot" rule. The steam account shown is on the community trusted list so I find it far more likely they simply had one of these characters in their name than tf2 does something funky with 200F to make it appear as a 202C or 200F

**Comment by ByThePowerOfScience** [comment]
Yep, turns out I was looking at a different listing.  Apparently that person is on the trustedbanlist.  According to her, it's cause one of the guys on there is stalking her.  If you have any control over that, I'd recommend you look into it, but it isn't a rule issue.

**Comment by ClusterConsultant** [comment]
I do have some control over it but I will not say who marked who. I recommend if anyone has an issue, to talk about it in the tf2bd discord, dm myself (The Immortal Nicholas Flamel#0001), or dm pazer (pazer#8137).
