### ISSUE TITLE
[BUG] Vote fails when TF2 in background

### ISSUE THREAD

**Issue by Dr-n00dle** [PazerOP/tf2_bot_detector#323]
**Describe the bug**
> When bot detector calls a vote and TF2 is minimised/in the background it fails
> %votereason% in the chat

**To Reproduce**
> alt-tab out of TF2
> wait for bot to join and vote to be called
> Vote fails with reason shown in screenshot

**Expected behavior**
> Vote should either succeed, or be delayed until TF2 is re-opened

**Logs**
> I cannot view them due to my other bug

**Screenshots**
> https://imgur.com/a/CNxlzIl

**Desktop (please complete the following information):**
> - OS: Windows 10
> - Version of bot detector 1.2.0.798

**Comment by Dr-n00dle** [comment]
[debug_report.zip](https://github.com/PazerOP/tf2_bot_detector/files/6447158/debug_report.zip)

**Comment by ClusterConsultant** [comment]
I am unable to reproduce this at all. In general that vote failed sign is a hud glitch. Try updating to the nightly build.
