### ISSUE TITLE
[BUG] Invalid TF2 command line arguments

### ISSUE THREAD

**Issue by Chris2918** [PazerOP/tf2_bot_detector#336]
![why](https://user-images.githubusercontent.com/37005770/123429303-cca25980-d594-11eb-8e41-98a8e885f490.PNG)
Whenever I launched TF2 with TF2 bot detector this happens
Didn't happen before now it happens
Why does it happen?

**Comment by DCxDemo** [comment]
same here

**Comment by GTcreyon** [comment]
This is already known, should be fixed in the latest nightly build.

**Comment by UAVXP** [comment]
Duplicate of #331

**Comment by PazerOP** [comment]
Duplicate of #331.

The fix for this should be rolling out to the preview channel sometime this evening, and the stable channel sometime tomorrow assuming there are no other major issues discovered.
