### ISSUE TITLE
[BUG] Bot Detector always fails to activate due to 'Invalid command line arguments'

### ISSUE THREAD

**Issue by RangerFrank** [PazerOP/tf2_bot_detector#337]
Bot Detector always fails to activate when launching TF2, it provides the error below:
![tf2bd](https://user-images.githubusercontent.com/14126780/123500707-4c0e5680-d683-11eb-8791-92498040c524.PNG)

This occurs despite any or no command line arguments. Neither Steam nor TF2 are set to run in Administrator mode.
TF2 Console gives this error:

Invalid rich presence string: " -usercon -high +developer 1 +alias developer +contimes 0 +alias contimes +ip 0.0.0.0 +alias ip +sv_rcon_whitelist_address 127.0.0.1 +alias sv_rcon_whitelist_address +sv_quota_stringcmdspersecond 1000000 +alias sv_quota_stringcmdspersecond +rcon_password oYbkYnLw4zqODykT +alias rcon_password +hostport 53907 +alias hostport +alias cl_reload_localization_files +net_start +con_timestamp 1 +alias con_timestamp -condebug -conclearlog"

For some reason I'm unable to upload my log file.

Microsoft Windows 10 Home 10.0.19042 Build 19042
TF2 BotDetector version 1.2.0.798

I haven't played in several months but previously had no issues.

**Comment by RangerFrank** [comment]
[2021-06-26_13-57-35.log.txt](https://github.com/PazerOP/tf2_bot_detector/files/6719548/2021-06-26_13-57-35.log.txt)

**Comment by ClusterConsultant** [comment]
#331 

update to nightly
