### ISSUE TITLE
[BUG] Entry Point Not Found: The procedure entry point GetCurrentThreadStackLimits could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by UAVXP** [PazerOP/tf2_bot_detector#339]
**Describe the bug**
TF2BD couldn't start on Windows 7 after 1.2.1.934 build, even on clean install. It shows an error messagebox with "Entry Point Not Found: The procedure entry point GetCurrentThreadStackLimits could not be located in the dynamic link library KERNEL32.dll" message

**To Reproduce**
1. Download the latest release (v1.2.1.934)
2. Run tf2_bot_detector.exe
3. The error from screenshot shows up

**Expected behavior**
On the previous build (1.2.0.798) the program runned fine

**Screenshots**
![image](https://user-images.githubusercontent.com/3075683/123552421-be179600-d77e-11eb-806a-2fa1e86e2202.png)

**Desktop (please complete the following information):**
- OS: Windows 7
- TF2BD v1.2.1.934

**Additional context**
All needed VC++ redists are installed, .NET Frameworks are too

**Comment by brachistosaurus** [comment]
Sorry. **Windows 7** hasn't been supported for a few months, already.

https://github.com/PazerOP/tf2_bot_detector/releases/tag/1.2.0.798 (January 17, 2021)

> In an effort to use current best practices for Windows development the installer and updater required the usage of the WinRT API. Unfortunately this API is not available on Windows 7. The work required to support a Windows 7 version and a Windows 10 version, including alternate code paths, testing, and user support is simply not something that the single developer is able to support.

> Windows 7 has reached "End Of Life" (EOL), which means Microsoft is no longer providing security or feature updates for it. New security vulnerabilities discovered in the OS will not be patched, bugs will never be fixed, and it is strongly recommended to upgrade to Windows 10 as soon as possible. According to the Steam Hardware Survey, Windows 7 now accounts for less than 4% of all PCs running Steam, and is on a steady decline.

**Comment by UAVXP** [comment]
That's too bad. My notebook couldn't handle Win 10 unfortunately... Well, it's been a wild ride then) Thanks so much for the program @PazerOP

**Comment by UAVXP** [comment]
Actually, I've compiled the program, so it's being able to work on Windows 7 right now)

**Comment by PazerOP** [comment]
Did you make changes to the code? Or just recompiling it was enough?

**Comment by UAVXP** [comment]
> Did you make changes to the code? Or just recompiling it was enough?

No, I made changes. I will send them here later, I have 10:00PM

**Comment by UAVXP** [comment]
Okay, here's the diff: https://pastebin.com/9neY1hQ3
