### ISSUE TITLE
When bot detector is set to launch TF2 on tool start, does not check if TF2 is running first

### ISSUE THREAD

**Issue by ClusterConsultant** [PazerOP/tf2_bot_detector#343]
If TF2 is opened by TF2BD, then TF2BD is closed and reopened TF2BD attempts to start hl2.exe a second time. TF2BD then waits for the user to close the source warning pop up and continues on to function normally. This seems to only happen when TF2BD is set to launch TF2 automatically.

**Comment by ClusterConsultant** [comment]
https://github.com/PazerOP/tf2_bot_detector/blob/8f42acd8fdb8245de54559ea072a754ae5dfd07a/tf2_bot_detector/SetupFlow/TF2CommandLinePage.cpp#L315
should probably check if tf2 is running first

**Comment by Link2006** [comment]
I would like to say that the issue persists as of 1.2.1.940 if TF2 is already launched but not via TF2BD as it seems to complain for a brief moment that it couldn't find the arguments before going back to the main screen when the source warning pops up 
![image](https://user-images.githubusercontent.com/984642/124180860-ca536a00-da82-11eb-865d-624467efff34.png)

**Comment by ClusterConsultant** [comment]
I mean, you do have to launch tf2 via tf2bd. Maybe some kind of warning is in order

**Comment by PazerOP** [comment]
Hopefully that should resolve all of these issues. If not, leave another message here.
