### ISSUE TITLE
detect namestealing bot using Levenshtein distance

### ISSUE THREAD

**Issue by Theexternaldisk** [PazerOP/tf2_bot_detector#345]
Name stealing are not detected because they always add a inviseble character to a (random) place inside the stolen name.
This causes bots that are not on the bot lists to slip through and ruin the game.

possible solution would be to check the name of joining bots/people with the already present names and calculate the Levenshtein distance (https://en.wikipedia.org/wiki/Levenshtein_distance). 
if the score is below a certain threshold mark them as suspicious or cheater. Although marking as cheater could be risky in case someone just happens to have a very similar name.

Would even be better to check if the names are the same in 'readable' characters and only differ in 'unreadable' characters

**Comment by ClusterConsultant** [comment]
#218 but I appreciate the mention of my favorite mathematican
