### ISSUE TITLE
windows 7 support

### ISSUE THREAD

**Issue by kotc** [PazerOP/tf2_bot_detector#347]
i know w7 is a minority, but i still prefer it over w10. since i'm an active tf2 player i would like to have working tbd. is there any chance of continuing support?

**Comment by PazerOP** [comment]
Windows 7 has reached EOL and is no longer receiving security updates. You should update as soon as possible.

Because it is EOL and incompatible with many of the modern APIs found on Microsoft platforms, it's no longer supported by TF2 Bot Detector.

**Comment by UAVXP** [comment]
> i know w7 is a minority, but i still prefer it over w10. since i'm an active tf2 player i would like to have working tbd. is there any chance of continuing support?

I can give you my compiled build of TF2BD, that is working on Win7
