### ISSUE TITLE
[BUG] The program does not start (Crash)

### ISSUE THREAD

**Issue by DustyFan** [PazerOP/tf2_bot_detector#348]
**Describe the bug**
> The program does not start

**To Reproduce**
> 1. Go to 'TF2 Bot Detector' (that's what I named the folder)
> 2. Click on 'tf2_bot_detector.exe'
> 3. 'tfbd_crash_2021-07-08-20-19-14.mdmp' appears in the folder

**Expected behavior**
> Crash.

**Logs**
> I'd love to, but I don't know where to find the logs without running the program.

**Screenshots**
> Don't need.

**Desktop:**
> - OS: Windows 10
> - Version of bot detector 1.2.1.934

**Additional context**
> An error window does not appear, the tf2bd simply does not start.
Here is the crash dump file:
[tfbd_crash_2021-07-08-20-19-14.zip](https://github.com/PazerOP/tf2_bot_detector/files/6795133/tfbd_crash_2021-07-08-20-19-14.zip)
(You asked me to make issue on GitHub, sorry for not doing it right away.)

**Comment by ClusterConsultant** [comment]
Does the path you are saving the unzipped dir to contain any non-ASCII characters?
