### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#351]
I would be asking this in the discord, but I still can't verify with my phone.

When a dude blatantly and proudly shows themselves associating with bots, and they have their steam account linked. That's justifiable to mark as a cheater, right?
![helping bots](https://user-images.githubusercontent.com/26986519/126396621-a1785208-8222-4526-ba51-5202fbe90eca.jpg)

**Comment by Jesseman1** [comment]
this dude has a weird Steam ID though, [U:1:0]
Never seen one so short before

**Comment by ClusterConsultant** [comment]
I would say this is up to you. In your position there aren't many repercussions for a false mark. The repo itself won't take community suggestions. I'll leave this open for comment from other community members for a few days.

**Comment by Jesseman1** [comment]
That's what I got from the ID finder when I put the account link into it

**Comment by Jesseman1** [comment]
ah, ok that ID finder just doesn't seem to work. Tried another one and got the right ID [U:1:373924589]

**Comment by Kenajcrap** [comment]
I wouldn't mark that person as a cheater. Since I haven't seen him cheating, just healing a bot (which was cheating, of course).
