### ISSUE TITLE
Make it like this

### ISSUE THREAD

**Issue by Barmem** [PazerOP/tf2_bot_detector#354]
![изображение](https://user-images.githubusercontent.com/70278808/127604789-c3137b6b-51b4-4cf8-bb23-5c1c8aab1445.png)

**Comment by ClusterConsultant** [comment]
what does this mean, what do you want

**Comment by Barmem** [comment]
make that button open it in steam
![изображение](https://user-images.githubusercontent.com/70278808/127605088-6c1d9728-21c3-40ad-b661-35306cbd0805.png)

**Comment by ClusterConsultant** [comment]
From a consistency standpoint I think it should open in the browser since that's where all the other links also open

Aren't those steam urls broken anyways?

**Comment by moebkun** [comment]
100% better to just open in browser - steam community is just a browser but bad anyways.

**Comment by Barmem** [comment]
> 
> 
> 100% better to just open in browser - steam community is just a browser but bad anyways.
Not really because it opens browser and someone like me has a bunch of tabs ready to eat all RAM and slow tf2 down

**Comment by BitmapDummy** [comment]
I'd like it to open in the client since I'm always logged into Steam there and not the browser since I clear cookies often.

**Comment by Barmem** [comment]
Seems like chaging it in settings file actually works, wierd, it didnt before
