### ISSUE TITLE
An auto-kick BOT only mode

### ISSUE THREAD

**Issue by AChristianGamer** [PazerOP/tf2_bot_detector#358]
I'm having trouble with kicking cheaters, because as soon as they join the program kicks them, but nobody else in the lobby knows why.  I've even been called a bot 7 minutes into the game, because the cheater used his microphone to act ticked off and surprised just after he joined and was kicked.  Also, auto-mark feature has been falsely marking people as cheaters, after they had been using their mikes to speak with each other.

A simple and effective solution would be to allow users to have full control of who they mark as cheaters, without other peoples input potentially muddying up the waters with false reports through the internet connection of the Official List.  Making the Official List as an optional download would be required.  But on the bright side, this program would no longer need to be updated as often, because we the users would be updating our own personal lists.

If this is not possible, then having a base version of this program to simply auto-kick specific accounts would be okay.

I hope I am not asking too much, I really love the work you've done Pazer, and I hope to see more amazing things from you in the future!

**Comment by brachistosaurus** [comment]
> A simple and effective solution would be to allow users to have full control of who they mark as cheaters, without other peoples input potentially muddying up the waters with false reports

A user's marks only affects their program. It doesn't affect yours.

**Comment by ClusterConsultant** [comment]
Also you can delete the official list if you don't want it.

See #318, #314, #255, and https://github.com/PazerOP/tf2_bot_detector#how-is-the-list-of-known-cheaters-curated
