### ISSUE TITLE
Option to customize chat messages

### ISSUE THREAD

**Issue by xXKSP-PlayerXx** [PazerOP/tf2_bot_detector#359]
Some bots use the same messages as the bot detector and thus confusing people into either:
- Kicking the wrong player
- Not trusting the messages sent by a real bot detector

A solution would be an option to customize chat messages. So it can look like a normal chat message sent by a real player. The bots name could be inserted with [target] or some similar statement.

**Comment by ClusterConsultant** [comment]
#70
