### ISSUE TITLE
Catching Friendly Cheaters.

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#362]
I still am unable to talk on the Discord, but I would like to add to the conversation in General about spectating teammates. Some cheaters will have their program tell them when they are being spectated, and who is watching. They can easily wait for the player watching them to respawn before resuming what they were doing. However, there is a console command to extend your respawn timer and let you spectate for as long as you want.

Bind 'extendfreeze' to any key you want and each time you press it, a few seconds will be added to your respawn timer while you are dead. You can use this command repeatedly to keep extending your timer and watching any teammate you suspect of cheating.

Remember, on official servers you are not told if someone is spectating you, if a teammate asks why you are spectating them without you ever telling them about it, they are using cheats.

**Comment by BitmapDummy** [comment]
Big if true. But how is this an issue?

**Comment by Jesseman1** [comment]
not an issue, this is just the only way I can contribute to the conversation, and I use this command myself often to spec suspicious players.

**Comment by ClusterConsultant** [comment]
Consider verifying your phone number.

**Comment by Jesseman1** [comment]
I have been trying to. Discord won't accept it and support is being extremely slow about helping.
