### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChairsWithWheels** [PazerOP/tf2_bot_detector#364]
**Describe the bug**
> A clear and concise description of what the bug is.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Logs**
> Add any relevant logs. Logs are found by going to File → Open Logs Folder

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
> - OS: [e.g. Windows 10, 8, 7]
> - Version of bot detector [e.g. 1.1.0.674]

**Additional context**
> Add any other context about the problem here.

**Comment by ClusterConsultant** [comment]
?
