### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#370]
**Describe the bug**
> I'm unsure where the issue is exactly but the bot detector and the master comfig seem to be clashing at the moment. With version 9.6.3 of mastercomfig and version 1.2.1.934 of TF2BD installed and running at the same time, the map voting window in TF2 bugs out and is not visible with the round end scoreboard. Instead it can only be accessed by pressing esc.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Install version 9.6.3 of mastercomfig on ultra preset.
> 2. install version 1.2.1.934 of TF2BD.
> 3. Play a full match in casual.
> 4. See missing voting window.

**Expected behavior**
> I expect the mastercomfig and TF2BD not to clash with each other, especially in this way.

**Screenshots**
> None currently but I can get some.

**Desktop (please complete the following information):**
> - OS: Windows 10
> - Version of bot detector: 1.2.1.934

**Additional context**
> I'm also using Toon HUD, I don't know if that would affect anything.

**Comment by ClusterConsultant** [comment]
Have you enabled the compatibility mode in tf2bd?
![image](https://user-images.githubusercontent.com/19409904/134105270-d4d31abd-606a-4a2f-b5e3-a1a25c3b089c.png)

**Comment by ClusterConsultant** [comment]
It should be noted, I use a config very similar to mastercomfig ultra, toonhud, and some funky other modules without any issues. This sounds closer to a hud problem than anything else which is not in scope for tf2bd

**Comment by Jesseman1** [comment]
yes, compatibility mode is enabled. I find it hard to put the blame on Toon Hud since i've had it for almost a year now with no issues, and the voting window appeared correctly when I launched TF2 without the detector.

**Comment by ClusterConsultant** [comment]
Does it work with the default hud?

**Comment by Jesseman1** [comment]
just tested. wow defualt hud looks so weird now. map voting seems to be working now. Maybe it was just a bug with TF2? I gotta finish homework before any more testing.

**Comment by ClusterConsultant** [comment]
BD doesn't really touch hud files. Only thing I can think of is the vote failed eraser which you can disable in settings.

**Comment by Jesseman1** [comment]
Must have been a TF2 bug cuz map voting is working just fine now.
