### ISSUE TITLE
Add option to copy Steam friend code for easy reporting bot accounts

### ISSUE THREAD

**Issue by alex-esc** [PazerOP/tf2_bot_detector#375]
Currently when you right click on a user you are able to copy the user's in game name and steam ID

The steam ID looks like this: `[U:1:1140848569]` but a useful feature to report bot accounts would be to parse the steam ID to show as a friend code (`1140848569` for example).

Currently I jump back and forth from server to server reporting bot accounts and the process is very repetitive: Right click on the user, copy steam ID, go to add a friend, paste their ID into the friend code, delete the `[U:1:` part and go to their profile and report them there.

If the author adds an option to copy a user's friend code along side copy user's name and steam ID this would make reporting bot accounts easier. This would also make it easier to add someone as a friend on the server.

**Comment by ClusterConsultant** [comment]
i don't see how this is different to the button that brings you to their steam page
