### ISSUE TITLE
Keybind request

### ISSUE THREAD

**Issue by SSJ3Bane** [PazerOP/tf2_bot_detector#376]
**A clear and concise description of what the problem is.**
> When using and checking out player cheaters, I dislike having the chat warnings spam, and it takes a minute to alt-tab due to fullscreen. Also, when if you're with a friend and you just want it off for the moment without having to alt-tab.

**Describe the solution you'd like**
> The ability the bind a combination of keys to toggle things like chat warnings, auto votekick, and automark. They could be blank by default.

**Describe alternatives you've considered**
> None, I honestly think keybinds, even optional ones, are always useful.

**Additional context**
> None really.

**Comment by ClusterConsultant** [comment]
#205 #207 and #282
