### ISSUE TITLE
Auto Voting No when bot tries to vote someone out?

### ISSUE THREAD

**Issue by McHKS** [PazerOP/tf2_bot_detector#380]
Hello,

Not sure this is even an option to do, but would there be some kind of way to auto vote no if a bot calls a vote?  Perhaps be able to discern if a bot calls a vote on an impersonated player?  If so, put out a chat message saying hit F2, a bot initiated the vote.

The chat messages are a little way too frequent too.  Perhaps an option to advise bot on other team, and if acknowledged in chat, make it like every couple of minutes?

**Comment by ClusterConsultant** [comment]
@Critical-Cookie is correct
