### ISSUE TITLE
Custom warning messages.

### ISSUE THREAD

**Issue by HatWearingMann** [PazerOP/tf2_bot_detector#385]
It would be a pretty good idea to implement custom chat warnings as the current one is also being used by cheaters which results in the user getting accused of cheating and/or kicked. It could be changed in the program's settings or the config file. As a bonus, there could be a team specific warning.

It could look something like this:

chatWarningEnemyBlu: "Hey blue team, you have a cheater named" botName ". Please kick him quick!"
chatWarningEnemyRed: "Hey red team, you have a cheater named" botName ". Please kick him quick!"
chatWarningAllyBlu: "Hey blue team, we have a cheater named" botName ". Please kick him quick!"
chatWarningAllyRed: "Hey red team, we have a cheater named" botName ". Please kick him quick!"

I don't know this coding language too well but I hope you get the gist.

**Comment by ClusterConsultant** [comment]
#70
