### ISSUE TITLE
Conflict with quick-switch bind [BUG]

### ISSUE THREAD

**Issue by arroyoquiel** [PazerOP/tf2_bot_detector#388]
An update of TF2 Bot Detector broke this script https://github.com/jooonior/tf2-loadouts-script and every time you try to quick-switch it doesn't recognize. Previously this bind worked.

How to replicate:
1. Open TF2 with TF2 Bot Detector
2. Join a match
3. When pressing the key that triggers quick-switch binds, it outputs an error in the console, for example: "Unknown command: loadouts.class.A" when trying to switch to loadout "A"

If you don't launch TF2 with the bot detector, the quick-switch bind works as intended.

OS: Windows 10
Version of the TF2 Bot Detector: v.1.2.1.949

I also have "Config Compatibility Mode" on.
This bug might have occurred after the 17th of March 2022 (this is the last good date of my saved_loadouts.txt).

**Comment by arroyoquiel** [comment]
The console gives me these messages when I am on a server and trying to use the quick-switch bind.

Msg from **SERVER_IP**: svc_UserMessage: type 16, bytes 17
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34
Unknown command: loadouts.A
Msg from **SERVER_IP**: svc_UserMessage: type 5, bytes 34

The text **SERVER_IP** is actually not in the output, I just changed the IP because I don't know if it's mine so...

**Comment by ClusterConsultant** [comment]
How did you resolve this?

**Comment by arroyoquiel** [comment]
> How did you resolve this?

It was an error on my end.
The cause of this was me updating Mastercomfig, I had edited a previous version and I changed the name of its "autoexec.cfg" to "mastercomfig_autoexec.cfg" because I have another vpk that also has an "autoexec" file so it creates a conflict, I forgot to do the same thing after updating it, so all I did now to fix it is renaming all the autoexec files in my vpks and executing them with the tf/cfg/autoexec.cfg.

exec mastercomfig_autoexec
exec custombinds_autoexec
