### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#393]
I was in a match the other day, enemy team was stacked with bots. We had one player on our team who was using blatant spinbot but he had set it up to only shoot the bots. They weren't marked on any list but I've been wondering if these players should be put on the list or not?

**Comment by Betawolfy** [comment]
you can manually mark a player as cheater if you want. If you consider anti bot as cheaters, you can mark them. if I remember correctly, the official list does not take any suggestions from users. I let a member correct me if needed. I hope I could help you.

**Comment by ClusterConsultant** [comment]
I have yet to run into someone who claims to only cheat against bots and also actually only kills bots. Generally, I mark them. Whether you do you not is purely up to you and project intention should not heavily influence your moral choices.
