### ISSUE TITLE
Automatically Disconnect While Loading Map if More than a Set Number of Bots are Detected

### ISSUE THREAD

**Issue by glarpo** [PazerOP/tf2_bot_detector#395]
I noticed that the program can Identify cheaters while loading into a map. (The "You're on your way to" / "Duel Score" Screen) 

Using this, you could automatically disconnect the player if the bot count is too high for them, completely skipping having to load into the map, picking a class, identifying if the game has bots, and then leaving. 

### **How Would It work?**
Users would have to enable a setting named "Disconnect If Bot Count Is Over the Specified Maximum". (Or something like that.) If that's enabled, two more options will appear under it. One asking users how many bots need to be in the game to be automatically disconnected, with the default being around 3. The other option will ask the user if they want to be automatically put in the queue if they are disconnected.

### **With those being enabled, an unsuccessful queue would go something like this:**
The user queues for casual with the max bot count set to 3, and the option to be automatically put in the queue when disconnected enabled. After waiting, a game is found, and the user loads into the map. Four bots are detected, so the user is disconnected and a sound effect plays letting the user know they were disconnected because too many bots were detected. Because the user has the option enabled, they will be put back into the queue for the maps they were originally searching for.

**Comment by ClusterConsultant** [comment]
#277 #389
