### ISSUE TITLE
botdetector.die ? 

### ISSUE THREAD

**Issue by CyberDruga** [PazerOP/tf2_bot_detector#396]
not an enhancement. just questioning if this can cause some problems for me

![image](https://user-images.githubusercontent.com/22626848/161410744-f6818de2-09f0-4dcc-9d2f-1e5bd32a511b.png)

It seems they created a detector for the botdetector, since he just joined in and immediately started spamming the mic, I couldn't even mute him since the screen kept updating nonstop.

**Comment by Jesseman1** [comment]
what do you mean you couldn't mute him? Did the normal in-game mute not work?
Also, detecting the bot detector is not new, they have scripts that pick up any time someone sends the warning message. Cheaters will put your name on a list, but it really makes no difference to gameplay. Having your name on a list doesn't make bots or cheaters target you any more than they already do.

**Comment by CyberDruga** [comment]
> what do you mean you couldn't mute him? Did the normal in-game mute not work?

The option on the main menu wouldn't open and right click menu on the scoreboard kept closing every type I opened it. 
Also it kicked everybody out of the server.

**Comment by Jesseman1** [comment]
huh. I thought Valve servers are supposed to be protected from attacks like that now. It sounds kind of like a DDoS on the server.

**Comment by CyberDruga** [comment]
> they have scripts that pick up any time someone sends the warning message

here is the thing, I keep this disabled since the message is in english and I play on Latin America servers, they probably detected that I tried to kick him.

> huh. I thought Valve servers are supposed to be protected from attacks like that now. It sounds kind of like a DDoS on the server.

This was not the first time, I ran into a cheater earlier that did the same thing, It kicks everyone out and after some time everybody comes back.

**Comment by UAVXP** [comment]
Not "kicks", but DDoSing Steam relay or the server itself for a short period of time, so all the clients, who has default cl_timeout value of 30 seconds just disconnects from it

**Comment by Jesseman1** [comment]
I'm not sure how they would know you have the detector unless you've used the chat warnings before. As for kicking everyone out, I've seen people mention you can avoid getting kicked by increasing your timeout from the default like UAVXP said.

**Comment by CyberDruga** [comment]
But anyway, you can close this issue if you want, I got my answer but I might confess that this was pretty scary, my luck was that I had only 4 kills and 12 deaths, plus they were spinning like crazy.

Anyhow, keep up the good work.

**Comment by ClusterConsultant** [comment]
> But anyway, you can close this issue if you want

most people close their own issues once they are resolved
