### ISSUE TITLE
Abandon joining a server that is loaded with bots (maybe even warn others?)

### ISSUE THREAD

**Issue by lohman** [PazerOP/tf2_bot_detector#399]
Thanks to TF2BD -for which I am very grateful thank you- I now cycle through joining several servers until I find one that is mostly people with 1-4 bots or fewer.  It seems like a great feature to have TF2BD do this join/abandon cycle automatically.  As soon as I click join, TF2BD populates with a list of players and starts madly flashing with bots.  When that happens, I'd love to have the option to have TF2BD automatically abandon that server and start a new join cycle.  Just join/abandon/join/abandon until it finds a server that fits my criteria.

Would prefer for this to be a configurable option with "percent bots" in the settings that trigger the cycle.

I wish I could code.  I'd love to help.  But absent that, I tell everyone about TF2BD.  Thank you so much for your work I really appreciate it.

**Comment by ClusterConsultant** [comment]
#277 #389 #395
