### ISSUE TITLE
Lauches TF2 > dies

### ISSUE THREAD

**Issue by LoonEc** [PazerOP/tf2_bot_detector#401]
After having the [same issues described in here](https://github.com/PazerOP/tf2_bot_detector/issues/400), I re-installed manually. TF2BotDetector will launch, tell me the host is down. After skipping that, and launching TF2, it will display this messages:

Invalid TF2 command line argument
Details:
- Instance: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\hl.exe -steam - game tf
 Unable to find "-usericon"
 Unable to find "+ip"
 Unable to find "+rcon_password"
 Unable to find "+hostport"

**Comment by ClusterConsultant** [comment]
You are probably running an out of date version. Consider using https://github.com/PazerOP/tf2_bot_detector/releases/tag/1.2.1.934

**Comment by Temmie-Flakes** [comment]
I have the same issue, but I got it working. The portable version doesn't work for me on windows 10 home but the windows msixbundle version works. 
This is what worked for me.
download the one labeled: "tf2-bot-detector_windows_1.2.1.934_Release.msixbundle" from 
https://github.com/PazerOP/tf2_bot_detector/releases/tag/1.2.1.934
Install it. Run it and change "Notify about new stable releases" to "Disable automatic update checks"
Close the program (might have to force close it from task manager).
Re open it and it works.
