### ISSUE TITLE
Doeshotter's main account

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#402]
I'm just going to leave this here, found his account by accident.
[U:1:451334419]
He's not marked on the detector but his account links to a private group with all his alts and his youtube channel.

**Comment by Jesseman1** [comment]
https://steamcommunity.com/id/DoesHotterLSD/ just in case anyone doesn't believe me about the account.

**Comment by Jazztache** [comment]
If you can add people by SteamID, you should probs add his alts. He's got a group of them on his profile.
