### ISSUE TITLE
[BUG] I'm being muted to myself after a few days using the program

### ISSUE THREAD

**Issue by Ashetf2** [PazerOP/tf2_bot_detector#409]
**Describe the bug**
Title. When I'm muted, I can't see my own messages

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Play a few days
> 2. You will be muted to yourself

**Expected behavior**
Nothing

**Logs**
> Add any relevant logs. Logs are found by going to File → Open Logs Folder

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
> - OS: [e.g. Windows 10, 8, 7]
> - Version of bot detector [e.g. 1.1.0.674]

**Additional context**
> If I delete the voice_ban.dt file in tf/, it works again

**Comment by Jesseman1** [comment]
I've had this happen to me a few times, though I don't think the program is causing it. In my case I've noticed a pattern where trying to mute a player while several people are leaving/joining and making the list of names move around would result in being muted to myself. It's easy to fix though, group select several names in the mute menu, including your own, mute them, then unmute them. This will unmute yourself as well.

**Comment by ClusterConsultant** [comment]
I don't believe this is possible as I'm pretty sure the code doesn't do anything around muting. I am unable to reproduce the issue and I have been running it quite a bit lately. This can be reopened if others come forward

**Comment by Ashetf2** [comment]
> I don't believe this is possible as I'm pretty sure the code doesn't do anything around muting. I am unable to reproduce the issue and I have been running it quite a bit lately. This can be reopened if others come forward

oh right, the program doesn't mute people. I guess that what happened is what Jesse said.
Edit: Yeah, that is what happened. It is already reported at https://github.com/ValveSoftware/Source-1-Games/issues/3396
