### ISSUE TITLE
Failed list update

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#410]
Hello, the bot detector program hasn't been able to update two of the main lists for about a year now. I can't talk on the discord so I'm hoping I can get some help here.

The first list is Milenko's list. I've since moved this list into an archive folder since I recall someone mentioning the list was being retired anyway.

The second list is the trusted list. I just saw Nicholas mention in the help and support channel that this list is being migrated, so hopefully that will be fixed soon?

I just want to make sure there's nothing broken with the program. I got it installed when the one-click installer still worked, and had updates until the website went down.

Here's the console response for the failed list update.
![Failed list update](https://user-images.githubusercontent.com/26986519/200090011-3ecd1831-f00f-43b7-9db8-ae700e875765.jpg)

**Comment by Tiagoquix** [comment]
https://github.com/PazerOP/tf2_bot_detector/issues/400
