### ISSUE TITLE
Add mark as bot

### ISSUE THREAD

**Issue by janechicken** [PazerOP/tf2_bot_detector#411]
**A clear and concise description of what the problem is.**
> I mark one bot but when another joins it isn't automatically kicked it has the same name but different steam user

**Describe the solution you'd like**
> Add a mark as bot option which kicks everyone with the name same as someone marked as a bot

**Describe alternatives you've considered**
> Just using the rule editor to mark anyone with a name

**Comment by ClusterConsultant** [comment]
This is covered by the rules system. UI management of rules is a separate problem
