### ISSUE TITLE
Questions about personal lists

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#412]
Ive been using the bot detector for almost three years now, and my personal list has grown ridiculously big. Now I'm certain that my list is at least 95% accurate, but there are some names on it that I'm just not sure about. I'd like to wipe my personal list, or move it somewhere else as an archive, and start a new one to make sure I'm not calling out anyone by mistake. Is there a simple way to make a new personal list? Do I just need to move my list somewhere else and the program will automatically create another one, or do I need to manually create a new file?

Secondly, and part of the reason I'd like to make a new list, I saw someone mention a 'proof' section that can be added under a name in the list. How does this work? What does it do? Is there documentation somewhere or a guide I can look at on how to implement it?

**Comment by ClusterConsultant** [comment]
> Do I just need to move my list somewhere else and the program will automatically create another one, or do I need to manually create a new file?

You should be able to simply delete it

> Secondly, and part of the reason I'd like to make a new list, I saw someone mention a 'proof' section that can be added under a name in the list. How does this work? What does it do? Is there documentation somewhere or a guide I can look at on how to implement it?

It is effectively a comment
https://github.com/PazerOP/tf2_bot_detector/blob/master/schemas/v3/playerlist.schema.json#L41
