### ISSUE TITLE
[BUG] Generating Chat Wrapper Hard Crash

### ISSUE THREAD

**Issue by HenryMigo** [PazerOP/tf2_bot_detector#419]
**Describe the bug**
> The application is hard crashing when generating chat wrapper.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Load exe
> 2. Skip updating
> 3. Generate chat wrapper gets to 19% then crashes
> 4. See error

**Expected behavior**
> The application to complete and load

**Logs**
> Add any relevant logs. Logs are found by going to File → Open Logs Folder
[tf2-bot-detector_x64-windows_1.2.1.934_Release.zip](https://github.com/PazerOP/tf2_bot_detector/files/11782051/tf2-bot-detector_x64-windows_1.2.1.934_Release.zip)

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![Error](https://github.com/PazerOP/tf2_bot_detector/assets/10053087/5b67c981-dbb0-42c2-8792-ca6467176650)

**Desktop (please complete the following information):**
> - OS: Windows 11
> - Version of bot detector 1.2.1.934

**Comment by Jesseman1** [comment]
The bot detector was not created for W11. I don't think anyone can help with this.

**Comment by surepy** [comment]
likely hud issue, change encoding of all of your chat resources in your hud (save it from utf-8 to utf-16)

located in ``tf/custom/(your hud)/resource/chat_*.txt``

see also: https://github.com/surepy/tf2_bot_detector/issues/6

**Comment by HenryMigo** [comment]
> likely hud issue, change encoding of all of your chat resources in your hud (save it from utf-8 to utf-16)
> 
> located in `tf/custom/(your hud)/resource/chat_*.txt`
> 
> see also: [surepy#6](https://github.com/surepy/tf2_bot_detector/issues/6)

They are UTF-16 LE

**Comment by HenryMigo** [comment]
I'll try removing the hud and see if that works

**Comment by HenryMigo** [comment]
Yeah it was the hud

**Comment by surepy** [comment]
yea just fix encoding for all the files and it should launch

**Comment by HenryMigo** [comment]
Issue found and resolved
