### ISSUE TITLE
[BUG] PazerOP is a Power Hungry Virgin Loser Advertising a Blatant Ineffective Malware

### ISSUE THREAD

**Issue by ghost** [PazerOP/tf2_bot_detector#423]
**Describe the bug**
> The title says it all. It's also bloated and sidetracks to unrelated marks that are not cheater or bot, so also false advertisement disguised as a 'solution' for gullible people not able to tell a cheater/bot and a real player apart believing random dudes that are not to be trusted if you do a little research so Matt Haynie can blackmail people he doesn't like.

**Expected behavior**
> Follow my project https://github.com/Tututerok/TF2-Bigot-Detector-Preventer (i actually know how to code unlike some child enthusiast)

**Additional context**
> https://www.youtube.com/watch?v=b0RrEE6q7sA&lc=UgzAax-jfWIW1tUG_ql4AaABAg

**Comment by Barmem** [comment]
look, cheater got angry, point and laugh at him

**Comment by Jesseman1** [comment]
Hahahahaha!

**Comment by Tututerok** [comment]
> look, cheater got angry, point and laugh at him

Sorry you got angry at me spittin' facts.
