### ISSUE TITLE
[Question] How do you even send commands to the client

### ISSUE THREAD

**Issue by home-gihub** [PazerOP/tf2_bot_detector#427]
I have been looking around everywhere but they all said about sending commands to the server, not the client.

**Comment by ChrisChrome** [comment]
Iirc the client has a launch argument that allows RCON connections just like the server
It's been a while since I've messed with it, so I don't know the flags off the top of my head.

**Comment by ChrisChrome** [comment]
> Iirc the client has a launch argument that allows RCON connections just like the server It's been a while since I've messed with it, so I don't know the flags off the top of my head.

There are some references to command line arguments when launching the client in this file, Id recommend taking a look there to get an idea of what you'd need to do to enable RCON on your client
https://github.com/PazerOP/tf2_bot_detector/blob/master/tf2_bot_detector/SetupFlow/TF2CommandLinePage.cpp

**Comment by home-gihub** [comment]
thx

**Comment by home-gihub** [comment]
I don't know what they do and I have no idea how th write c++

**Comment by ClusterConsultant** [comment]
The client and the server are very similar applications, nearly identical. TF2BD uses rcon as described in https://developer.valvesoftware.com/wiki/Source_RCON_Protocol. As ChrisChrome pointed out, https://github.com/PazerOP/tf2_bot_detector/blob/44f7a803d5dce93ad4f8aa9f1fd83b4ffffae625/tf2_bot_detector/SetupFlow/TF2CommandLinePage.cpp#L212-L230 those are the flags tf2bd uses. Depending on what you are trying to do, the discord server may be more verbose about a specific implementation

**Comment by home-gihub** [comment]
I don't have discord.
