### ISSUE TITLE
Cannot Open

### ISSUE THREAD

**Issue by DarksniperJuinor** [PazerOP/tf2_bot_detector#44]
I'm trying to open the program to throw it offscreen and it won't open

**Comment by ClusterConsultant** [comment]
We are going to need some more details to help you. Does it produce an error message? Are you using the latest version? Did you install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019?

**Comment by PazerOP** [comment]
Sorry for the initial delay in responding, but I'm going to close this issue since it appears dead. If you are still experiencing problems, feel free to make a new issue or bring it up on discord.
