### ISSUE TITLE
"sleep when unfocused" disabled raises cpu when minimized

### ISSUE THREAD

**Issue by hoffr** [PazerOP/tf2_bot_detector#54]
with the game closed (haven't tried it with it on yet), when the option "sleep when unfocused" is disabled, the program actually seems to use far more cpu (up to 4x) while minimized vs when focused. simply unfocusing doesn't make cpu high, it must be minimized

**Comment by ClusterConsultant** [comment]
After testing with the most recent version I am not able to reproduce. Can you give it a test on the most recent release to see if this is still an issue?

**Comment by ClusterConsultant** [comment]
This issue will be closed on 25/01/2021 if nothing more is heard
