### ISSUE TITLE
False Accusations 

### ISSUE THREAD

**Issue by CoolEvan** [PazerOP/tf2_bot_detector#65]
I've been advised by a reddit user to flag this up on here, though I think it's quite a common error and we are early stages.

During my match there was a bot on the enemy team and the automatic messaging feature was calling out 5 separate members of the enemy team who were certainly not botting, otherwise the bot seemed to work as intended however it is infuriating constantly seeing the vote cooldown message on your screen as you are trying to play the game.

Thank you

**Comment by PazerOP** [comment]
Thanks for the heads up. I am aware of this issue, and it's already been fixed for v1.1.

**Comment by ClusterConsultant** [comment]
> 
> 
> Thanks for the heads up. I am aware of this issue, and it's already been fixed for v1.1.

closing
