### ISSUE TITLE
Using the Steam API

### ISSUE THREAD

**Issue by g1b3r1sh** [PazerOP/tf2_bot_detector#72]
Using the steam API can help differentiate between bots and real users. For example:

- As steam accounts need to spend money in order to gain levels, using the API to get the user level can prevent false bot marking. (http://api.steampowered.com/IPlayerService/GetSteamLevel/v1/?key=&steamid=)
- The account creation date of a profile can be taken from the 'timecreated' field in unix time at http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=&steamids=
  - While the API doesn't retrieve account creation dates for private accounts (among other things), since newer steamIDs are higher than old ones, a nearby account can be checked for its creation date instead.

A limitation of using the steam API is that it is limited to 100 000 requests per day, but that shouldn't be a big problem unless the user uses another application that also uses the steam API.

**Comment by DiegoFleitas** [comment]
Unless you assume all private profiles are hackers (a bad assumption) I don't see this being useful, I think the best endpoint to request for this tool would be https://api.steampowered.com/ISteamUser/GetPlayerBans/v1/ to check if a player has been VAC banned on other source games.

**Comment by g1b3r1sh** [comment]
Since the API can get the account creation date of a player, it could mark new accounts as suspicious and alert the user. It could also be used to reduce the number of false-positives caused by the bot manipulating the console.log file through chat if another method is found in the future, as a user with a high level wouldn't act like a bot.

Although the API doesn't return lots of information on private profiles, their approximate account creation date can still be tracked through their SteamID, the API could still be used passively (eg. detecting genuine players, detecting accounts that haven't been setup yet).

**Comment by PazerOP** [comment]
Thanks for this. Web-based integrations are going to come in future versions.

**Comment by ParzivalWolfram** [comment]
Please note that this doesn't take into account people using free toolkits that force a name, or people who've been account-jacked and may result in false-negatives. I'd suggest merely weighting the user on these lines, and not absolutely clearing them on it.

**Comment by PazerOP** [comment]
I'm not sure what you mean by "account-jacked", but you're correct that this is just being used as some extra information to show the user, not automated [un]marking. It's very simple to get your steam nickname to not match your ingame name, most of the time you can just change your steam name and it won't update ingame for some time.

**Comment by ParzivalWolfram** [comment]
> I'm not sure what you mean by "account-jacked", but you're correct that this is just being used as some extra information to show the user, not automated [un]marking. It's very simple to get your steam nickname to not match your ingame name, most of the time you can just change your steam name and it won't update ingame for some time.

"People that have their accounts stolen and access sold" is what I meant. My bad.

**Comment by ClusterConsultant** [comment]
#184 is related

**Comment by ClusterConsultant** [comment]
API usage is in a decent place right now. Further specific features should probably be their own issue so it can be tracked.
