### ISSUE TITLE
New myg0t bots are not marked automatically.

### ISSUE THREAD

**Issue by GolfinhoVoador** [PazerOP/tf2_bot_detector#74]
One bot has: "[g0tb0t]" and the other one has: "[t0gym]" in the start of the username, You can detect [g0tb0t] by adding homophobic words in the official rules.

_I dont think they spam their link though._

**Fact check: they do spam their link, But it doens't auto mark them.**

**Comment by GolfinhoVoador** [comment]
[t0gym] bots are a thing too.
These make anti-muslim comment

**Comment by Scarlette564** [comment]
for now you can mark them yourself by clicking on their name and marking them as "cheater", this will stay in your list and always vote kick them.

**Comment by ClusterConsultant** [comment]
Latest version has detection rules, closing
