### ISSUE TITLE
Implement autobuild with azure pipelines or github actions ? (Probably the same)

### ISSUE THREAD

**Issue by Xephobia** [PazerOP/tf2_bot_detector#79]
Hi, it would be cool if you implement an autobuild system for this repo, so people can have a "nightly" release. I can provide you an azure dev ops yaml, i can also try for github actions but i'm more familiar with azure dev ops.

**Comment by PazerOP** [comment]
I'm planning to set up github actions soon.

**Comment by Xephobia** [comment]
i can help you with that, simply give me the build steps

**Comment by PazerOP** [comment]
Thanks. A (work-in-progress) cmake project is on the cmake branch. It's still windows-specific at this point, but I'll work on that once I get a chance. It currently has external dependencies on SDL2 and glbinding, which I'm (locally) getting through vcpkg. As far as I know, that shouldn't cause issues with github actions?
