### ISSUE TITLE
Add auto-deny and add auto-confirm

### ISSUE THREAD

**Issue by DareFox** [PazerOP/tf2_bot_detector#84]
Add auto-deny when bot is trying to kick someone and add auto-confirm when another user start vote for kick bot

**Comment by DareFox** [comment]
Add auto-deny when bot is trying to kick someone and add auto-confirm when another user start vote for kick bot

**Comment by lnx00** [comment]
Afaik this isn't possible. You aren't able to detect a vote using the console log.

**Comment by DareFox** [comment]
:c

**Comment by ClusterConsultant** [comment]
Not possible

**Comment by PazerOP** [comment]
To clarify: votes don't show up in the console log in any meaningful detail, and the only way I'd be able to figure out who is calling the vote and who is the target is via demo parsing. That has a fair amount of delay though, so the vote would probably be mostly over before we figured out if we wanted to vote yes or no.
