### ISSUE TITLE
Using a normal script to send commands rather than -hijack

### ISSUE THREAD

**Issue by The-personified-devil** [PazerOP/tf2_bot_detector#88]
If I'm right, the application works through reading data out of the console.log file. The application is also based on basic console commands. These can not just be executed through some weird hijack process or through the console, but also through in-game scripts. ~~The whole is just taking a complicated approach at a little loop in autoexec.cfg.~~ This would also enable the use of the application on Linux, since it is no longer dependent on the `hijack` argument.

~~I don't see anything, that speaks against using this method. It would have a lesser impact on performance. As far as problems with `wait` being disabled on certain servers, I don't think, that's a problem, because casual servers have it enabled and it would be against the mentality of community servers. I mean it would be awkward having `sv_pure 0` but deactivating `wait`.~~
The truth is that casual servers have `wait` enabled and casual community servers are basically not attacked by bots and mostly have actually working anti-cheats installed.
I hope this method could be used ~~instead.~~ to make a sketchy version that is working on linux. You would have to have the user set it up and it would have to control the game with fake key presses (this could be used as an alternative timer rather than wait) and constantly editing the single file that is being accessed. 

P.S: Please fix the 100 temporary script files bulking up because of this tool.

**Comment by ClusterConsultant** [comment]
Will be part of the new rcon method. Please make a separate issue for different issues.

**Comment by PazerOP** [comment]
@The-personified-devil I really would like to hear about the "100 temporary script files" you mention. Please do make an issue about that if you have a chance.

**Comment by The-personified-devil** [comment]
The tool would rack up a good amount of files to send commands to the game to (I think it went away later on).
I will close this, because the whole idea is now obsolete (Thanks to the better implementation).

**Comment by PazerOP** [comment]
All right then. Those files should have been getting deleted every time the tool was launched, but won't be generated at all now that RCON is in.
