### ISSUE TITLE
[Enhancement] Add an icon to the executable

### ISSUE THREAD

**Issue by CrazyGunman2C4U** [PazerOP/tf2_bot_detector#92]
Pictures for the People

I suggest adding an icon to both make the application appear more "friendly" and to make clear how it can serve the user. 

~~At best, you pay someone for the next Killer-App Icon or have people throw great content (at you) and clothes (on the stage) because of your popularity. Reality sucks tho, you'll have to take what an amateur can offer you.~~

This unique, precious thing combines the box from your day-to-day votekicking experience and adds your trusty heavy bot of choice to it.

[TBD.zip](https://github.com/PazerOP/tf2_bot_detector/files/4794286/TBD.zip)

If you are interested in a blank heavy bot, we can deliver!

![robot_head](https://user-images.githubusercontent.com/53367662/84932219-411a0100-b0d4-11ea-9cfb-57446fded0a4.png)

If you want to laugh at an pathetic attempt to add an existing killicon to it, you won't be disappointed! Might be bad enough for an April Fools Special Edition(TM).

[TBD-Mannico.zip](https://github.com/PazerOP/tf2_bot_detector/files/4794306/TBD-Mannico.zip)

Based on this idea from The Mango Man

[votein.zip](https://github.com/PazerOP/tf2_bot_detector/files/4794319/votein.zip)

On a more serious side: Any icon will do. I just had some fun.

EDIT: My suggestion is adding the TBD.ico from TBD.zip The heavy bot image could be displayed directly, but the .ico files weren't supported and had to be zipped.

**Comment by PazerOP** [comment]
Thanks for your efforts! I would have added yours, but [S-Purple](https://twitter.com/spurpleheart) (NSFW) contacted me and offered to make some artwork for TF2BD. I decided to use his artwork for the icon. 
![image](https://user-images.githubusercontent.com/6569500/85216695-a112e080-b33c-11ea-90dc-2375192def9c.png)
