### ISSUE TITLE
Change the message that is put in chat when a bot joins the other team

### ISSUE THREAD

**Issue by Spygineer2** [PazerOP/tf2_bot_detector#97]
I would like to change the message to "kick your bot", or just disable the message in chat.

**Comment by karlovchap** [comment]
just disable chat messages in your copy of TF2BD, Spygineer

**Comment by DiegoFleitas** [comment]
I made a similar request too https://github.com/PazerOP/tf2_bot_detector/issues/70

**Comment by ClusterConsultant** [comment]
Duplicate of issue #70
